pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = "670166063118.dkr.ecr.ap-south-2.amazonaws.com/srirepo"
        EKS_CLUSTER_NAME = "sri-eks"
        AWS_REGION = "ap-south-2"
    }
    stages {
        stage('Fetch source code') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/THOTASRIHARI506/blaze.git']]])
                
            }
        }
    }
     }
        stage('Build Maven project') {
         steps {
                sh 'mvn clean package'
            }
        }
     
    
        stage('Build Docker image') {
            steps {
                sh 'docker build -t srirepo:marine .'
            }
        }
        stage('Push Docker image to registry') {
            steps {

                    sh "aws ecr get-login-password --region ap-south-2 | docker login --username AWS    --password-stdin 670166063118.dkr.ecr.ap-south-2.amazonaws.com"
                  sh  " docker tag srirepo:marine 670166063118.dkr.ecr.ap-south-2.amazonaws.com/srirepo:marine"
                    sh " docker push 670166063118.dkr.ecr.ap-south-2.amazonaws.com/srirepo:marine"
                }
            }
        
        stage('Deploy to EKS cluster') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'sri-eks', namespace: '', restrictKubeConfigAccess: false, serverUrl: '') {
                    sh "aws eks update-kubeconfig --region ap-south-2 --name sri-eks"
                    sh 'kubectl get svc '
                    sh 'kubectl apply -f marine.yaml'
                }
            }
        }
    




