apiVersion: v1
kind: Service
metadata:
  name: marine
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: marine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marine-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marine
  template:
    metadata:
      labels:
        app: marine
        version: marine-version-1
    spec:
      containers:
      - name: adok8-1
        image: 670166063118.dkr.ecr.ap-south-2.amazonaws.com/srirepo:marine
        imagePullPolicy: Always
        env:
           - name: TZ
             value: Asia/Kolkata      

