//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CancellationCharges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellationCharges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cancellationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="cancellationType" type="{http://marine.icicilombard.com}CancellationType"/>
 *         &lt;element name="cancellationEndorseType" type="{http://marine.icicilombard.com}CancellationEndorseType"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cancellationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="validPeriod" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="cancellationCharge" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cancellationFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="retainPremium" type="{http://marine.icicilombard.com}RetainFlag"/>
 *         &lt;element name="premiumAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="refundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="retainAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="retainAmountWithCancellationCharges" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cancellationTaxDetails" type="{http://marine.icicilombard.com}TaxDetails"/>
 *         &lt;element name="stampDutyChargable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="stampDuty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellationCharges", propOrder = {
    "cancellationDate",
    "cancellationType",
    "cancellationEndorseType",
    "productCode",
    "cancellationRequired",
    "validPeriod",
    "cancellationCharge",
    "cancellationFlag",
    "retainPremium",
    "premiumAmount",
    "refundAmount",
    "retainAmount",
    "retainAmountWithCancellationCharges",
    "cancellationTaxDetails",
    "stampDutyChargable",
    "stampDuty"
})
public class CancellationCharges
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date cancellationDate;
    @XmlElement(required = true)
    protected CancellationType cancellationType;
    @XmlElement(required = true)
    protected CancellationEndorseType cancellationEndorseType;
    @XmlElement(required = true)
    protected String productCode;
    protected boolean cancellationRequired;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date validPeriod;
    @XmlElement(required = true)
    protected BigDecimal cancellationCharge;
    protected boolean cancellationFlag;
    @XmlElement(required = true)
    protected RetainFlag retainPremium;
    @XmlElement(required = true)
    protected BigDecimal premiumAmount;
    @XmlElement(required = true)
    protected BigDecimal refundAmount;
    @XmlElement(required = true)
    protected BigDecimal retainAmount;
    @XmlElement(required = true)
    protected BigDecimal retainAmountWithCancellationCharges;
    @XmlElement(required = true)
    protected TaxDetails cancellationTaxDetails;
    protected boolean stampDutyChargable;
    @XmlElement(required = true)
    protected BigDecimal stampDuty;

    /**
     * Gets the value of the cancellationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCancellationDate() {
        return cancellationDate;
    }

    /**
     * Sets the value of the cancellationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationDate(Date value) {
        this.cancellationDate = value;
    }

    /**
     * Gets the value of the cancellationType property.
     * 
     * @return
     *     possible object is
     *     {@link CancellationType }
     *     
     */
    public CancellationType getCancellationType() {
        return cancellationType;
    }

    /**
     * Sets the value of the cancellationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellationType }
     *     
     */
    public void setCancellationType(CancellationType value) {
        this.cancellationType = value;
    }

    /**
     * Gets the value of the cancellationEndorseType property.
     * 
     * @return
     *     possible object is
     *     {@link CancellationEndorseType }
     *     
     */
    public CancellationEndorseType getCancellationEndorseType() {
        return cancellationEndorseType;
    }

    /**
     * Sets the value of the cancellationEndorseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellationEndorseType }
     *     
     */
    public void setCancellationEndorseType(CancellationEndorseType value) {
        this.cancellationEndorseType = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the cancellationRequired property.
     * 
     */
    public boolean isCancellationRequired() {
        return cancellationRequired;
    }

    /**
     * Sets the value of the cancellationRequired property.
     * 
     */
    public void setCancellationRequired(boolean value) {
        this.cancellationRequired = value;
    }

    /**
     * Gets the value of the validPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getValidPeriod() {
        return validPeriod;
    }

    /**
     * Sets the value of the validPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidPeriod(Date value) {
        this.validPeriod = value;
    }

    /**
     * Gets the value of the cancellationCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCancellationCharge() {
        return cancellationCharge;
    }

    /**
     * Sets the value of the cancellationCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCancellationCharge(BigDecimal value) {
        this.cancellationCharge = value;
    }

    /**
     * Gets the value of the cancellationFlag property.
     * 
     */
    public boolean isCancellationFlag() {
        return cancellationFlag;
    }

    /**
     * Sets the value of the cancellationFlag property.
     * 
     */
    public void setCancellationFlag(boolean value) {
        this.cancellationFlag = value;
    }

    /**
     * Gets the value of the retainPremium property.
     * 
     * @return
     *     possible object is
     *     {@link RetainFlag }
     *     
     */
    public RetainFlag getRetainPremium() {
        return retainPremium;
    }

    /**
     * Sets the value of the retainPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetainFlag }
     *     
     */
    public void setRetainPremium(RetainFlag value) {
        this.retainPremium = value;
    }

    /**
     * Gets the value of the premiumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremiumAmount() {
        return premiumAmount;
    }

    /**
     * Sets the value of the premiumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremiumAmount(BigDecimal value) {
        this.premiumAmount = value;
    }

    /**
     * Gets the value of the refundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * Sets the value of the refundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRefundAmount(BigDecimal value) {
        this.refundAmount = value;
    }

    /**
     * Gets the value of the retainAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetainAmount() {
        return retainAmount;
    }

    /**
     * Sets the value of the retainAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetainAmount(BigDecimal value) {
        this.retainAmount = value;
    }

    /**
     * Gets the value of the retainAmountWithCancellationCharges property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetainAmountWithCancellationCharges() {
        return retainAmountWithCancellationCharges;
    }

    /**
     * Sets the value of the retainAmountWithCancellationCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetainAmountWithCancellationCharges(BigDecimal value) {
        this.retainAmountWithCancellationCharges = value;
    }

    /**
     * Gets the value of the cancellationTaxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetails }
     *     
     */
    public TaxDetails getCancellationTaxDetails() {
        return cancellationTaxDetails;
    }

    /**
     * Sets the value of the cancellationTaxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetails }
     *     
     */
    public void setCancellationTaxDetails(TaxDetails value) {
        this.cancellationTaxDetails = value;
    }

    /**
     * Gets the value of the stampDutyChargable property.
     * 
     */
    public boolean isStampDutyChargable() {
        return stampDutyChargable;
    }

    /**
     * Sets the value of the stampDutyChargable property.
     * 
     */
    public void setStampDutyChargable(boolean value) {
        this.stampDutyChargable = value;
    }

    /**
     * Gets the value of the stampDuty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStampDuty() {
        return stampDuty;
    }

    /**
     * Sets the value of the stampDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStampDuty(BigDecimal value) {
        this.stampDuty = value;
    }

}
