//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClauseDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClauseDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clauseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clauseCodeReplaceWith" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clauseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClauseDetails", propOrder = {
    "clauseCode",
    "clauseCodeReplaceWith",
    "clauseName",
    "operation"
})
public class ClauseDetails
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected String clauseCode;
    @XmlElement(required = true)
    protected String clauseCodeReplaceWith;
    @XmlElement(required = true)
    protected String clauseName;
    @XmlElement(required = true)
    protected String operation;

    /**
     * Gets the value of the clauseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseCode() {
        return clauseCode;
    }

    /**
     * Sets the value of the clauseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseCode(String value) {
        this.clauseCode = value;
    }

    /**
     * Gets the value of the clauseCodeReplaceWith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseCodeReplaceWith() {
        return clauseCodeReplaceWith;
    }

    /**
     * Sets the value of the clauseCodeReplaceWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseCodeReplaceWith(String value) {
        this.clauseCodeReplaceWith = value;
    }

    /**
     * Gets the value of the clauseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseName() {
        return clauseName;
    }

    /**
     * Sets the value of the clauseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseName(String value) {
        this.clauseName = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

}
