//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EquationsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquationsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="basicODRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="basicTrailerODRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="fixedODPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="basicTPPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="basicTPPremium_GcvMisd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ncbRemarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvalTriggerFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="noOfClaim" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="idvRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="exceptionalDetails" type="{http://marine.icicilombard.com}ExceptionalScenarios" maxOccurs="unbounded"/>
 *         &lt;element name="tpExceptionalDetails" type="{http://marine.icicilombard.com}ExceptionalScenarios" minOccurs="0"/>
 *         &lt;element name="channelLoading_Discount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquationsResponse", propOrder = {
    "basicODRate",
    "basicTrailerODRate",
    "fixedODPremium",
    "basicTPPremium",
    "basicTPPremiumGcvMisd",
    "ncbRemarks",
    "approvalTriggerFlag",
    "noOfClaim",
    "idvRate",
    "exceptionalDetails",
    "tpExceptionalDetails",
    "channelLoadingDiscount"
})
public class EquationsResponse
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected BigDecimal basicODRate;
    @XmlElement(required = true)
    protected BigDecimal basicTrailerODRate;
    @XmlElement(required = true)
    protected BigDecimal fixedODPremium;
    @XmlElement(required = true)
    protected BigDecimal basicTPPremium;
    @XmlElement(name = "basicTPPremium_GcvMisd", required = true)
    protected BigDecimal basicTPPremiumGcvMisd;
    @XmlElement(required = true)
    protected String ncbRemarks;
    protected boolean approvalTriggerFlag;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer noOfClaim;
    @XmlElement(required = true)
    protected BigDecimal idvRate;
    @XmlElement(required = true)
    protected com.icicilombard.marine.model.ExceptionalScenarios[] exceptionalDetails;
    protected com.icicilombard.marine.model.ExceptionalScenarios tpExceptionalDetails;
    @XmlElement(name = "channelLoading_Discount")
    protected BigDecimal channelLoadingDiscount;

    /**
     * Gets the value of the basicODRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicODRate() {
        return basicODRate;
    }

    /**
     * Sets the value of the basicODRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicODRate(BigDecimal value) {
        this.basicODRate = value;
    }

    /**
     * Gets the value of the basicTrailerODRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicTrailerODRate() {
        return basicTrailerODRate;
    }

    /**
     * Sets the value of the basicTrailerODRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicTrailerODRate(BigDecimal value) {
        this.basicTrailerODRate = value;
    }

    /**
     * Gets the value of the fixedODPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFixedODPremium() {
        return fixedODPremium;
    }

    /**
     * Sets the value of the fixedODPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFixedODPremium(BigDecimal value) {
        this.fixedODPremium = value;
    }

    /**
     * Gets the value of the basicTPPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicTPPremium() {
        return basicTPPremium;
    }

    /**
     * Sets the value of the basicTPPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicTPPremium(BigDecimal value) {
        this.basicTPPremium = value;
    }

    /**
     * Gets the value of the basicTPPremiumGcvMisd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicTPPremiumGcvMisd() {
        return basicTPPremiumGcvMisd;
    }

    /**
     * Sets the value of the basicTPPremiumGcvMisd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicTPPremiumGcvMisd(BigDecimal value) {
        this.basicTPPremiumGcvMisd = value;
    }

    /**
     * Gets the value of the ncbRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcbRemarks() {
        return ncbRemarks;
    }

    /**
     * Sets the value of the ncbRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcbRemarks(String value) {
        this.ncbRemarks = value;
    }

    /**
     * Gets the value of the approvalTriggerFlag property.
     * 
     */
    public boolean isApprovalTriggerFlag() {
        return approvalTriggerFlag;
    }

    /**
     * Sets the value of the approvalTriggerFlag property.
     * 
     */
    public void setApprovalTriggerFlag(boolean value) {
        this.approvalTriggerFlag = value;
    }

    /**
     * Gets the value of the noOfClaim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getNoOfClaim() {
        return noOfClaim;
    }

    /**
     * Sets the value of the noOfClaim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfClaim(Integer value) {
        this.noOfClaim = value;
    }

    /**
     * Gets the value of the idvRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIdvRate() {
        return idvRate;
    }

    /**
     * Sets the value of the idvRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIdvRate(BigDecimal value) {
        this.idvRate = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public com.icicilombard.marine.model.ExceptionalScenarios[] getExceptionalDetails() {
        if (this.exceptionalDetails == null) {
            return new com.icicilombard.marine.model.ExceptionalScenarios[ 0 ] ;
        }
        com.icicilombard.marine.model.ExceptionalScenarios[] retVal = new com.icicilombard.marine.model.ExceptionalScenarios[this.exceptionalDetails.length] ;
        System.arraycopy(this.exceptionalDetails, 0, retVal, 0, this.exceptionalDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public com.icicilombard.marine.model.ExceptionalScenarios getExceptionalDetails(int idx) {
        if (this.exceptionalDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.exceptionalDetails[idx];
    }

    public int getExceptionalDetailsLength() {
        if (this.exceptionalDetails == null) {
            return  0;
        }
        return this.exceptionalDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public void setExceptionalDetails(com.icicilombard.marine.model.ExceptionalScenarios[] values) {
        int len = values.length;
        this.exceptionalDetails = ((com.icicilombard.marine.model.ExceptionalScenarios[]) new com.icicilombard.marine.model.ExceptionalScenarios[len] );
        for (int i = 0; (i<len); i ++) {
            this.exceptionalDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public com.icicilombard.marine.model.ExceptionalScenarios setExceptionalDetails(int idx, com.icicilombard.marine.model.ExceptionalScenarios value) {
        return this.exceptionalDetails[idx] = value;
    }

    /**
     * Gets the value of the tpExceptionalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public com.icicilombard.marine.model.ExceptionalScenarios getTpExceptionalDetails() {
        return tpExceptionalDetails;
    }

    /**
     * Sets the value of the tpExceptionalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.ExceptionalScenarios }
     *     
     */
    public void setTpExceptionalDetails(com.icicilombard.marine.model.ExceptionalScenarios value) {
        this.tpExceptionalDetails = value;
    }

    /**
     * Gets the value of the channelLoadingDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChannelLoadingDiscount() {
        return channelLoadingDiscount;
    }

    /**
     * Sets the value of the channelLoadingDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChannelLoadingDiscount(BigDecimal value) {
        this.channelLoadingDiscount = value;
    }

}
