//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExcessDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcessDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="excessCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excessName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excessMinimumPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="excessMinimumPercentageReplaceValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="excessMinimumPercentageOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excessMinimumValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="excessMinimumValueReplaceValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="excessMinimumValueOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deductibleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deductibleTypeReplaceValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deductibleTypeOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcessDetails", propOrder = {
    "excessCode",
    "excessName",
    "excessMinimumPercentage",
    "excessMinimumPercentageReplaceValue",
    "excessMinimumPercentageOperation",
    "excessMinimumValue",
    "excessMinimumValueReplaceValue",
    "excessMinimumValueOperation",
    "deductibleType",
    "deductibleTypeReplaceValue",
    "deductibleTypeOperation"
})
public class ExcessDetails
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected String excessCode;
    @XmlElement(required = true)
    protected String excessName;
    @XmlElement(required = true)
    protected BigDecimal excessMinimumPercentage;
    @XmlElement(required = true)
    protected BigDecimal excessMinimumPercentageReplaceValue;
    @XmlElement(required = true)
    protected String excessMinimumPercentageOperation;
    @XmlElement(required = true)
    protected BigDecimal excessMinimumValue;
    @XmlElement(required = true)
    protected BigDecimal excessMinimumValueReplaceValue;
    @XmlElement(required = true)
    protected String excessMinimumValueOperation;
    @XmlElement(required = true)
    protected String deductibleType;
    @XmlElement(required = true)
    protected String deductibleTypeReplaceValue;
    @XmlElement(required = true)
    protected String deductibleTypeOperation;

    /**
     * Gets the value of the excessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessCode() {
        return excessCode;
    }

    /**
     * Sets the value of the excessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessCode(String value) {
        this.excessCode = value;
    }

    /**
     * Gets the value of the excessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessName() {
        return excessName;
    }

    /**
     * Sets the value of the excessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessName(String value) {
        this.excessName = value;
    }

    /**
     * Gets the value of the excessMinimumPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessMinimumPercentage() {
        return excessMinimumPercentage;
    }

    /**
     * Sets the value of the excessMinimumPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessMinimumPercentage(BigDecimal value) {
        this.excessMinimumPercentage = value;
    }

    /**
     * Gets the value of the excessMinimumPercentageReplaceValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessMinimumPercentageReplaceValue() {
        return excessMinimumPercentageReplaceValue;
    }

    /**
     * Sets the value of the excessMinimumPercentageReplaceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessMinimumPercentageReplaceValue(BigDecimal value) {
        this.excessMinimumPercentageReplaceValue = value;
    }

    /**
     * Gets the value of the excessMinimumPercentageOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessMinimumPercentageOperation() {
        return excessMinimumPercentageOperation;
    }

    /**
     * Sets the value of the excessMinimumPercentageOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessMinimumPercentageOperation(String value) {
        this.excessMinimumPercentageOperation = value;
    }

    /**
     * Gets the value of the excessMinimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessMinimumValue() {
        return excessMinimumValue;
    }

    /**
     * Sets the value of the excessMinimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessMinimumValue(BigDecimal value) {
        this.excessMinimumValue = value;
    }

    /**
     * Gets the value of the excessMinimumValueReplaceValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessMinimumValueReplaceValue() {
        return excessMinimumValueReplaceValue;
    }

    /**
     * Sets the value of the excessMinimumValueReplaceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessMinimumValueReplaceValue(BigDecimal value) {
        this.excessMinimumValueReplaceValue = value;
    }

    /**
     * Gets the value of the excessMinimumValueOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessMinimumValueOperation() {
        return excessMinimumValueOperation;
    }

    /**
     * Sets the value of the excessMinimumValueOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessMinimumValueOperation(String value) {
        this.excessMinimumValueOperation = value;
    }

    /**
     * Gets the value of the deductibleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeductibleType() {
        return deductibleType;
    }

    /**
     * Sets the value of the deductibleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeductibleType(String value) {
        this.deductibleType = value;
    }

    /**
     * Gets the value of the deductibleTypeReplaceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeductibleTypeReplaceValue() {
        return deductibleTypeReplaceValue;
    }

    /**
     * Sets the value of the deductibleTypeReplaceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeductibleTypeReplaceValue(String value) {
        this.deductibleTypeReplaceValue = value;
    }

    /**
     * Gets the value of the deductibleTypeOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeductibleTypeOperation() {
        return deductibleTypeOperation;
    }

    /**
     * Sets the value of the deductibleTypeOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeductibleTypeOperation(String value) {
        this.deductibleTypeOperation = value;
    }

}
