//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GSTTotalDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GSTTotalDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalCGSTAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalSGSTAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalIGSTAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalUTGSTAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalGSTAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalSBCAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalKKCAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation1Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation2Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation3Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation4Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation5Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totaltaxation6Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="otherTaxesAmountTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalTaxBlockLevel" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="finalAmountBlockLevel" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GSTTotalDetails", propOrder = {
    "totalCGSTAmount",
    "totalSGSTAmount",
    "totalIGSTAmount",
    "totalUTGSTAmount",
    "totalGSTAmount",
    "totalSBCAmount",
    "totalKKCAmount",
    "totaltaxation1Amount",
    "totaltaxation2Amount",
    "totaltaxation3Amount",
    "totaltaxation4Amount",
    "totaltaxation5Amount",
    "totaltaxation6Amount",
    "otherTaxesAmountTotal",
    "totalTaxBlockLevel",
    "finalAmountBlockLevel"
})
public class GSTTotalDetails
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected BigDecimal totalCGSTAmount;
    @XmlElement(required = true)
    protected BigDecimal totalSGSTAmount;
    @XmlElement(required = true)
    protected BigDecimal totalIGSTAmount;
    @XmlElement(required = true)
    protected BigDecimal totalUTGSTAmount;
    @XmlElement(required = true)
    protected BigDecimal totalGSTAmount;
    @XmlElement(required = true)
    protected BigDecimal totalSBCAmount;
    @XmlElement(required = true)
    protected BigDecimal totalKKCAmount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation1Amount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation2Amount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation3Amount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation4Amount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation5Amount;
    @XmlElement(required = true)
    protected BigDecimal totaltaxation6Amount;
    @XmlElement(required = true)
    protected BigDecimal otherTaxesAmountTotal;
    @XmlElement(required = true)
    protected BigDecimal totalTaxBlockLevel;
    @XmlElement(required = true)
    protected BigDecimal finalAmountBlockLevel;

    /**
     * Gets the value of the totalCGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalCGSTAmount() {
        return totalCGSTAmount;
    }

    /**
     * Sets the value of the totalCGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalCGSTAmount(BigDecimal value) {
        this.totalCGSTAmount = value;
    }

    /**
     * Gets the value of the totalSGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSGSTAmount() {
        return totalSGSTAmount;
    }

    /**
     * Sets the value of the totalSGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSGSTAmount(BigDecimal value) {
        this.totalSGSTAmount = value;
    }

    /**
     * Gets the value of the totalIGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIGSTAmount() {
        return totalIGSTAmount;
    }

    /**
     * Sets the value of the totalIGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIGSTAmount(BigDecimal value) {
        this.totalIGSTAmount = value;
    }

    /**
     * Gets the value of the totalUTGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalUTGSTAmount() {
        return totalUTGSTAmount;
    }

    /**
     * Sets the value of the totalUTGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalUTGSTAmount(BigDecimal value) {
        this.totalUTGSTAmount = value;
    }

    /**
     * Gets the value of the totalGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalGSTAmount() {
        return totalGSTAmount;
    }

    /**
     * Sets the value of the totalGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalGSTAmount(BigDecimal value) {
        this.totalGSTAmount = value;
    }

    /**
     * Gets the value of the totalSBCAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSBCAmount() {
        return totalSBCAmount;
    }

    /**
     * Sets the value of the totalSBCAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSBCAmount(BigDecimal value) {
        this.totalSBCAmount = value;
    }

    /**
     * Gets the value of the totalKKCAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalKKCAmount() {
        return totalKKCAmount;
    }

    /**
     * Sets the value of the totalKKCAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalKKCAmount(BigDecimal value) {
        this.totalKKCAmount = value;
    }

    /**
     * Gets the value of the totaltaxation1Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation1Amount() {
        return totaltaxation1Amount;
    }

    /**
     * Sets the value of the totaltaxation1Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation1Amount(BigDecimal value) {
        this.totaltaxation1Amount = value;
    }

    /**
     * Gets the value of the totaltaxation2Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation2Amount() {
        return totaltaxation2Amount;
    }

    /**
     * Sets the value of the totaltaxation2Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation2Amount(BigDecimal value) {
        this.totaltaxation2Amount = value;
    }

    /**
     * Gets the value of the totaltaxation3Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation3Amount() {
        return totaltaxation3Amount;
    }

    /**
     * Sets the value of the totaltaxation3Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation3Amount(BigDecimal value) {
        this.totaltaxation3Amount = value;
    }

    /**
     * Gets the value of the totaltaxation4Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation4Amount() {
        return totaltaxation4Amount;
    }

    /**
     * Sets the value of the totaltaxation4Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation4Amount(BigDecimal value) {
        this.totaltaxation4Amount = value;
    }

    /**
     * Gets the value of the totaltaxation5Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation5Amount() {
        return totaltaxation5Amount;
    }

    /**
     * Sets the value of the totaltaxation5Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation5Amount(BigDecimal value) {
        this.totaltaxation5Amount = value;
    }

    /**
     * Gets the value of the totaltaxation6Amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaltaxation6Amount() {
        return totaltaxation6Amount;
    }

    /**
     * Sets the value of the totaltaxation6Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaltaxation6Amount(BigDecimal value) {
        this.totaltaxation6Amount = value;
    }

    /**
     * Gets the value of the otherTaxesAmountTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherTaxesAmountTotal() {
        return otherTaxesAmountTotal;
    }

    /**
     * Sets the value of the otherTaxesAmountTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherTaxesAmountTotal(BigDecimal value) {
        this.otherTaxesAmountTotal = value;
    }

    /**
     * Gets the value of the totalTaxBlockLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTaxBlockLevel() {
        return totalTaxBlockLevel;
    }

    /**
     * Sets the value of the totalTaxBlockLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTaxBlockLevel(BigDecimal value) {
        this.totalTaxBlockLevel = value;
    }

    /**
     * Gets the value of the finalAmountBlockLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalAmountBlockLevel() {
        return finalAmountBlockLevel;
    }

    /**
     * Sets the value of the finalAmountBlockLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalAmountBlockLevel(BigDecimal value) {
        this.finalAmountBlockLevel = value;
    }

}
