//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for InstallmentExcessDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstallmentExcessDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="noOfInstallments" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="installmentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="installmentDetails" type="{http://marine.icicilombard.com}InstallmentDetails" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallmentExcessDetails", propOrder = {
    "noOfInstallments",
    "installmentPremium",
    "installmentDetails"
})
public class InstallmentExcessDetails
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer noOfInstallments;
    @XmlElement(required = true)
    protected BigDecimal installmentPremium;
    @XmlElement(required = true)
    protected com.icicilombard.marine.model.InstallmentDetails[] installmentDetails;

    /**
     * Gets the value of the noOfInstallments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getNoOfInstallments() {
        return noOfInstallments;
    }

    /**
     * Sets the value of the noOfInstallments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfInstallments(Integer value) {
        this.noOfInstallments = value;
    }

    /**
     * Gets the value of the installmentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstallmentPremium() {
        return installmentPremium;
    }

    /**
     * Sets the value of the installmentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstallmentPremium(BigDecimal value) {
        this.installmentPremium = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.InstallmentDetails }
     *     
     */
    public com.icicilombard.marine.model.InstallmentDetails[] getInstallmentDetails() {
        if (this.installmentDetails == null) {
            return new com.icicilombard.marine.model.InstallmentDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.InstallmentDetails[] retVal = new com.icicilombard.marine.model.InstallmentDetails[this.installmentDetails.length] ;
        System.arraycopy(this.installmentDetails, 0, retVal, 0, this.installmentDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.InstallmentDetails }
     *     
     */
    public com.icicilombard.marine.model.InstallmentDetails getInstallmentDetails(int idx) {
        if (this.installmentDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.installmentDetails[idx];
    }

    public int getInstallmentDetailsLength() {
        if (this.installmentDetails == null) {
            return  0;
        }
        return this.installmentDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.InstallmentDetails }
     *     
     */
    public void setInstallmentDetails(com.icicilombard.marine.model.InstallmentDetails[] values) {
        int len = values.length;
        this.installmentDetails = ((com.icicilombard.marine.model.InstallmentDetails[]) new com.icicilombard.marine.model.InstallmentDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.installmentDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.InstallmentDetails }
     *     
     */
    public com.icicilombard.marine.model.InstallmentDetails setInstallmentDetails(int idx, com.icicilombard.marine.model.InstallmentDetails value) {
        return this.installmentDetails[idx] = value;
    }

}
