//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MarineRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarineRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product" type="{http://marine.icicilombard.com}Product"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QuoteStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commodityRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverApplicable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="intermediaryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iLLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hubLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="userRoles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="policyStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="policyEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="policyType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="taxEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="taxDetails" type="{http://marine.icicilombard.com}TaxDetails"/>
 *         &lt;element name="modeOfConveyance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brokeragePercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="excessPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="consignmentValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="riInwardFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applyDiscOnTurnOverRate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="discOnTurnOverRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loadingOnTurnOverRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dealID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backdationDetails" type="{http://marine.icicilombard.com}BackdationDetails" minOccurs="0"/>
 *         &lt;element name="selectedBothBasicAndSRCC" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="intermediaryStorageApplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="intermediaryStorageDays" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="endorsementFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="endorsementNinetyFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="endorsementFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="endorsementNetRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="endorsementEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="productParameters" type="{http://marine.icicilombard.com}Parameters" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="txnType" type="{http://marine.icicilombard.com}TxnType"/>
 *         &lt;element name="coInsurance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="exceptionFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="instalmentFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="option" type="{http://marine.icicilombard.com}Option"/>
 *         &lt;element name="targetPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarineRequest", propOrder = {
    "product",
    "requestID",
    "quoteStatus",
    "commodityRequest",
    "coverApplicable",
    "intermediaryCode",
    "ilLocation",
    "hubLocation",
    "employeeID",
    "imid",
    "userType",
    "userRoles",
    "policyStartDate",
    "policyEndDate",
    "policyType",
    "taxEffectiveDate",
    "taxDetails",
    "modeOfConveyance",
    "brokeragePercentage",
    "excessPercentage",
    "consignmentValue",
    "riInwardFlag",
    "applyDiscOnTurnOverRate",
    "discOnTurnOverRate",
    "loadingOnTurnOverRate",
    "channel",
    "dealID",
    "backdationDetails",
    "selectedBothBasicAndSRCC",
    "intermediaryStorageApplicable",
    "intermediaryStorageDays",
    "endorsementFlag",
    "endorsementNinetyFivePercentRate",
    "endorsementFivePercentRate",
    "endorsementNetRate",
    "endorsementEffectiveDate",
    "productParameters",
    "txnType",
    "coInsurance",
    "transactionDate",
    "exceptionFlag",
    "instalmentFlag",
    "option",
    "targetPremium"
})
public class MarineRequest
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(name = "Product", required = true)
    protected Product product;
    @XmlElement(required = true)
    protected String requestID;
    @XmlElement(name = "QuoteStatus", required = true)
    protected String quoteStatus;
    @XmlElement(required = true)
    protected String commodityRequest;
    @XmlElement(required = true)
    protected String coverApplicable;
    @XmlElement(required = true)
    protected String intermediaryCode;
    @XmlElement(name = "iLLocation", required = true)
    protected String ilLocation;
    @XmlElement(required = true)
    protected String hubLocation;
    @XmlElement(required = true)
    protected String employeeID;
    @XmlElement(name = "IMID", required = true)
    protected String imid;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer userType;
    @XmlElement(required = true)
    protected String userRoles;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date policyStartDate;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date policyEndDate;
    protected Object policyType;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date taxEffectiveDate;
    @XmlElement(required = true)
    protected TaxDetails taxDetails;
    @XmlElement(required = true)
    protected String modeOfConveyance;
    protected BigDecimal brokeragePercentage;
    protected BigDecimal excessPercentage;
    protected BigDecimal consignmentValue;
    @XmlElement(required = true)
    protected String riInwardFlag;
    protected Boolean applyDiscOnTurnOverRate;
    protected BigDecimal discOnTurnOverRate;
    protected BigDecimal loadingOnTurnOverRate;
    @XmlElement(required = true)
    protected String channel;
    @XmlElement(required = true)
    protected String dealID;
    protected BackdationDetails backdationDetails;
    protected boolean selectedBothBasicAndSRCC;
    protected boolean intermediaryStorageApplicable;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer intermediaryStorageDays;
    protected Boolean endorsementFlag;
    protected BigDecimal endorsementNinetyFivePercentRate;
    protected BigDecimal endorsementFivePercentRate;
    protected BigDecimal endorsementNetRate;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date endorsementEffectiveDate;
    protected com.icicilombard.marine.model.Parameters[] productParameters;
    @XmlElement(required = true)
    protected TxnType txnType;
    @XmlElement(required = true)
    protected String coInsurance;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date transactionDate;
    protected boolean exceptionFlag;
    protected boolean instalmentFlag;
    @XmlElement(required = true)
    protected Option option;
    protected BigDecimal targetPremium;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the quoteStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteStatus() {
        return quoteStatus;
    }

    /**
     * Sets the value of the quoteStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteStatus(String value) {
        this.quoteStatus = value;
    }

    /**
     * Gets the value of the commodityRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityRequest() {
        return commodityRequest;
    }

    /**
     * Sets the value of the commodityRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityRequest(String value) {
        this.commodityRequest = value;
    }

    /**
     * Gets the value of the coverApplicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverApplicable() {
        return coverApplicable;
    }

    /**
     * Sets the value of the coverApplicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverApplicable(String value) {
        this.coverApplicable = value;
    }

    /**
     * Gets the value of the intermediaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediaryCode() {
        return intermediaryCode;
    }

    /**
     * Sets the value of the intermediaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediaryCode(String value) {
        this.intermediaryCode = value;
    }

    /**
     * Gets the value of the ilLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getILLocation() {
        return ilLocation;
    }

    /**
     * Sets the value of the ilLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setILLocation(String value) {
        this.ilLocation = value;
    }

    /**
     * Gets the value of the hubLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHubLocation() {
        return hubLocation;
    }

    /**
     * Sets the value of the hubLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHubLocation(String value) {
        this.hubLocation = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the imid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMID() {
        return imid;
    }

    /**
     * Sets the value of the imid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMID(String value) {
        this.imid = value;
    }

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserType(Integer value) {
        this.userType = value;
    }

    /**
     * Gets the value of the userRoles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRoles() {
        return userRoles;
    }

    /**
     * Sets the value of the userRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRoles(String value) {
        this.userRoles = value;
    }

    /**
     * Gets the value of the policyStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPolicyStartDate() {
        return policyStartDate;
    }

    /**
     * Sets the value of the policyStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyStartDate(Date value) {
        this.policyStartDate = value;
    }

    /**
     * Gets the value of the policyEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPolicyEndDate() {
        return policyEndDate;
    }

    /**
     * Sets the value of the policyEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyEndDate(Date value) {
        this.policyEndDate = value;
    }

    /**
     * Gets the value of the policyType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPolicyType() {
        return policyType;
    }

    /**
     * Sets the value of the policyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPolicyType(Object value) {
        this.policyType = value;
    }

    /**
     * Gets the value of the taxEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getTaxEffectiveDate() {
        return taxEffectiveDate;
    }

    /**
     * Sets the value of the taxEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxEffectiveDate(Date value) {
        this.taxEffectiveDate = value;
    }

    /**
     * Gets the value of the taxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetails }
     *     
     */
    public TaxDetails getTaxDetails() {
        return taxDetails;
    }

    /**
     * Sets the value of the taxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetails }
     *     
     */
    public void setTaxDetails(TaxDetails value) {
        this.taxDetails = value;
    }

    /**
     * Gets the value of the modeOfConveyance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeOfConveyance() {
        return modeOfConveyance;
    }

    /**
     * Sets the value of the modeOfConveyance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeOfConveyance(String value) {
        this.modeOfConveyance = value;
    }

    /**
     * Gets the value of the brokeragePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBrokeragePercentage() {
        return brokeragePercentage;
    }

    /**
     * Sets the value of the brokeragePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBrokeragePercentage(BigDecimal value) {
        this.brokeragePercentage = value;
    }

    /**
     * Gets the value of the excessPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessPercentage() {
        return excessPercentage;
    }

    /**
     * Sets the value of the excessPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessPercentage(BigDecimal value) {
        this.excessPercentage = value;
    }

    /**
     * Gets the value of the consignmentValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsignmentValue() {
        return consignmentValue;
    }

    /**
     * Sets the value of the consignmentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsignmentValue(BigDecimal value) {
        this.consignmentValue = value;
    }

    /**
     * Gets the value of the riInwardFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiInwardFlag() {
        return riInwardFlag;
    }

    /**
     * Sets the value of the riInwardFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiInwardFlag(String value) {
        this.riInwardFlag = value;
    }

    /**
     * Gets the value of the applyDiscOnTurnOverRate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplyDiscOnTurnOverRate() {
        return applyDiscOnTurnOverRate;
    }

    /**
     * Sets the value of the applyDiscOnTurnOverRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplyDiscOnTurnOverRate(Boolean value) {
        this.applyDiscOnTurnOverRate = value;
    }

    /**
     * Gets the value of the discOnTurnOverRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscOnTurnOverRate() {
        return discOnTurnOverRate;
    }

    /**
     * Sets the value of the discOnTurnOverRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscOnTurnOverRate(BigDecimal value) {
        this.discOnTurnOverRate = value;
    }

    /**
     * Gets the value of the loadingOnTurnOverRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoadingOnTurnOverRate() {
        return loadingOnTurnOverRate;
    }

    /**
     * Sets the value of the loadingOnTurnOverRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoadingOnTurnOverRate(BigDecimal value) {
        this.loadingOnTurnOverRate = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the dealID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealID() {
        return dealID;
    }

    /**
     * Sets the value of the dealID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealID(String value) {
        this.dealID = value;
    }

    /**
     * Gets the value of the backdationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BackdationDetails }
     *     
     */
    public BackdationDetails getBackdationDetails() {
        return backdationDetails;
    }

    /**
     * Sets the value of the backdationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackdationDetails }
     *     
     */
    public void setBackdationDetails(BackdationDetails value) {
        this.backdationDetails = value;
    }

    /**
     * Gets the value of the selectedBothBasicAndSRCC property.
     * 
     */
    public boolean isSelectedBothBasicAndSRCC() {
        return selectedBothBasicAndSRCC;
    }

    /**
     * Sets the value of the selectedBothBasicAndSRCC property.
     * 
     */
    public void setSelectedBothBasicAndSRCC(boolean value) {
        this.selectedBothBasicAndSRCC = value;
    }

    /**
     * Gets the value of the intermediaryStorageApplicable property.
     * 
     */
    public boolean isIntermediaryStorageApplicable() {
        return intermediaryStorageApplicable;
    }

    /**
     * Sets the value of the intermediaryStorageApplicable property.
     * 
     */
    public void setIntermediaryStorageApplicable(boolean value) {
        this.intermediaryStorageApplicable = value;
    }

    /**
     * Gets the value of the intermediaryStorageDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getIntermediaryStorageDays() {
        return intermediaryStorageDays;
    }

    /**
     * Sets the value of the intermediaryStorageDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediaryStorageDays(Integer value) {
        this.intermediaryStorageDays = value;
    }

    /**
     * Gets the value of the endorsementFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEndorsementFlag() {
        return endorsementFlag;
    }

    /**
     * Sets the value of the endorsementFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEndorsementFlag(Boolean value) {
        this.endorsementFlag = value;
    }

    /**
     * Gets the value of the endorsementNinetyFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndorsementNinetyFivePercentRate() {
        return endorsementNinetyFivePercentRate;
    }

    /**
     * Sets the value of the endorsementNinetyFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndorsementNinetyFivePercentRate(BigDecimal value) {
        this.endorsementNinetyFivePercentRate = value;
    }

    /**
     * Gets the value of the endorsementFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndorsementFivePercentRate() {
        return endorsementFivePercentRate;
    }

    /**
     * Sets the value of the endorsementFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndorsementFivePercentRate(BigDecimal value) {
        this.endorsementFivePercentRate = value;
    }

    /**
     * Gets the value of the endorsementNetRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndorsementNetRate() {
        return endorsementNetRate;
    }

    /**
     * Sets the value of the endorsementNetRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndorsementNetRate(BigDecimal value) {
        this.endorsementNetRate = value;
    }

    /**
     * Gets the value of the endorsementEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getEndorsementEffectiveDate() {
        return endorsementEffectiveDate;
    }

    /**
     * Sets the value of the endorsementEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndorsementEffectiveDate(Date value) {
        this.endorsementEffectiveDate = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.Parameters }
     *     
     */
    public com.icicilombard.marine.model.Parameters[] getProductParameters() {
        if (this.productParameters == null) {
            return new com.icicilombard.marine.model.Parameters[ 0 ] ;
        }
        com.icicilombard.marine.model.Parameters[] retVal = new com.icicilombard.marine.model.Parameters[this.productParameters.length] ;
        System.arraycopy(this.productParameters, 0, retVal, 0, this.productParameters.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.Parameters }
     *     
     */
    public com.icicilombard.marine.model.Parameters getProductParameters(int idx) {
        if (this.productParameters == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.productParameters[idx];
    }

    public int getProductParametersLength() {
        if (this.productParameters == null) {
            return  0;
        }
        return this.productParameters.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.Parameters }
     *     
     */
    public void setProductParameters(com.icicilombard.marine.model.Parameters[] values) {
        int len = values.length;
        this.productParameters = ((com.icicilombard.marine.model.Parameters[]) new com.icicilombard.marine.model.Parameters[len] );
        for (int i = 0; (i<len); i ++) {
            this.productParameters[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.Parameters }
     *     
     */
    public com.icicilombard.marine.model.Parameters setProductParameters(int idx, com.icicilombard.marine.model.Parameters value) {
        return this.productParameters[idx] = value;
    }

    /**
     * Gets the value of the txnType property.
     * 
     * @return
     *     possible object is
     *     {@link TxnType }
     *     
     */
    public TxnType getTxnType() {
        return txnType;
    }

    /**
     * Sets the value of the txnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnType }
     *     
     */
    public void setTxnType(TxnType value) {
        this.txnType = value;
    }

    /**
     * Gets the value of the coInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoInsurance() {
        return coInsurance;
    }

    /**
     * Sets the value of the coInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoInsurance(String value) {
        this.coInsurance = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(Date value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the exceptionFlag property.
     * 
     */
    public boolean isExceptionFlag() {
        return exceptionFlag;
    }

    /**
     * Sets the value of the exceptionFlag property.
     * 
     */
    public void setExceptionFlag(boolean value) {
        this.exceptionFlag = value;
    }

    /**
     * Gets the value of the instalmentFlag property.
     * 
     */
    public boolean isInstalmentFlag() {
        return instalmentFlag;
    }

    /**
     * Sets the value of the instalmentFlag property.
     * 
     */
    public void setInstalmentFlag(boolean value) {
        this.instalmentFlag = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link Option }
     *     
     */
    public Option getOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link Option }
     *     
     */
    public void setOption(Option value) {
        this.option = value;
    }

    /**
     * Gets the value of the targetPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetPremium() {
        return targetPremium;
    }

    /**
     * Sets the value of the targetPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetPremium(BigDecimal value) {
        this.targetPremium = value;
    }

}
