//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MarineResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarineResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uwLevel" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="approverAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="policyStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="basicRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="rackRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="netRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalDiscount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalLoading" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="serviceTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="stampDuty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="netPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="finalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pmlLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="messages" type="{http://marine.icicilombard.com}Messages"/>
 *         &lt;element name="rackAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="basicPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessNetPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessTotalPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessStampDuty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessNinetyFivePercentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessNinetyFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessFivePercentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nilExcessTaxDetails" type="{http://marine.icicilombard.com}TaxDetails"/>
 *         &lt;element name="installmentExcessDetails" type="{http://marine.icicilombard.com}InstallmentExcessDetails" minOccurs="0"/>
 *         &lt;element name="taxDetails" type="{http://marine.icicilombard.com}TaxDetails"/>
 *         &lt;element name="targetPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="targetRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="targetPremiumFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="targetRateFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="loadingFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="discountFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PSLFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PLLFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="sumInsuredFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="intermediaryStorageFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="backdationFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="clausesFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="warrantiesFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="excessFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="superDeviationCargoFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="questionnaireMasterFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="excessAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="brokeragePremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="customDutySI" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="policyRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="backdationDetails" type="{http://marine.icicilombard.com}BackdationDetails" minOccurs="0"/>
 *         &lt;element name="ninetyFivePerPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fivePercentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ninetyFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="dutyCOverPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="intermediaryStoragePremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="intermediaryStorageRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="minimumPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="finalAuthorityRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvaAuthorityStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="warrantyDetails" type="{http://marine.icicilombard.com}WarrantyDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="excessDetails" type="{http://marine.icicilombard.com}ExcessDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clauseDetails" type="{http://marine.icicilombard.com}ClauseDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subCommodityDetails" type="{http://marine.icicilombard.com}SubCommodityDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="marineCoverDetails" type="{http://marine.icicilombard.com}MarineCoverDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subProductsResponse" type="{http://marine.icicilombard.com}SubProduct" maxOccurs="unbounded"/>
 *         &lt;element name="totalExposurepremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalSalesExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalPurchaseExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalExposureRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stampDutyRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stopNetPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="purchaseExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="domesticPurchaseExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="domesticSalesExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="exportSalesExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="importPurchaseExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stopTurnOverRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalStopPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stopPolicyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalBrokeragePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalSumInsured" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="exposureSumInsured" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stopTurnOverRateBfrDisc" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stopTurnOverRateAftrDisc" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="equationsDetails" type="{http://marine.icicilombard.com}EquationsResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarineResponse", propOrder = {
    "uwLevel",
    "approverAuthority",
    "totalPremium",
    "requestID",
    "policyStatus",
    "basicRate",
    "rackRate",
    "netRate",
    "totalDiscount",
    "totalLoading",
    "serviceTax",
    "stampDuty",
    "netPremium",
    "finalRate",
    "pmlLimit",
    "messages",
    "rackAmount",
    "basicPremium",
    "nilExcessRate",
    "nilExcessNetPremium",
    "nilExcessTotalPremium",
    "nilExcessStampDuty",
    "nilExcessNinetyFivePercentPremium",
    "nilExcessNinetyFivePercentRate",
    "nilExcessFivePercentPremium",
    "nilExcessFivePercentRate",
    "nilExcessTaxDetails",
    "installmentExcessDetails",
    "taxDetails",
    "targetPremium",
    "targetRate",
    "targetPremiumFlag",
    "targetRateFlag",
    "loadingFlag",
    "discountFlag",
    "pslFlag",
    "pllFlag",
    "sumInsuredFlag",
    "intermediaryStorageFlag",
    "backdationFlag",
    "clausesFlag",
    "warrantiesFlag",
    "excessFlag",
    "superDeviationCargoFlag",
    "questionnaireMasterFlag",
    "excessAmount",
    "brokeragePremium",
    "customDutySI",
    "policyRate",
    "backdationDetails",
    "ninetyFivePerPremium",
    "fivePercentPremium",
    "ninetyFivePercentRate",
    "fivePercentRate",
    "dutyCOverPremium",
    "intermediaryStoragePremium",
    "intermediaryStorageRate",
    "minimumPremium",
    "finalAuthorityRole",
    "userId",
    "approvaAuthorityStatus",
    "warrantyDetails",
    "excessDetails",
    "clauseDetails",
    "subCommodityDetails",
    "marineCoverDetails",
    "subProductsResponse",
    "totalExposurepremium",
    "totalSalesExposurePremium",
    "totalPurchaseExposurePremium",
    "totalExposureRate",
    "stampDutyRate",
    "stopNetPremium",
    "purchaseExposurePremium",
    "domesticPurchaseExposurePremium",
    "domesticSalesExposurePremium",
    "exportSalesExposurePremium",
    "importPurchaseExposurePremium",
    "stopTurnOverRate",
    "totalStopPremium",
    "stopPolicyType",
    "totalBrokeragePremium",
    "totalSumInsured",
    "exposureSumInsured",
    "stopTurnOverRateBfrDisc",
    "stopTurnOverRateAftrDisc",
    "equationsDetails"
})
public class MarineResponse
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer uwLevel;
    @XmlElement(required = true)
    protected String approverAuthority;
    @XmlElement(required = true)
    protected BigDecimal totalPremium;
    @XmlElement(required = true)
    protected Object requestID;
    @XmlElement(required = true)
    protected String policyStatus;
    @XmlElement(required = true)
    protected BigDecimal basicRate;
    @XmlElement(required = true)
    protected BigDecimal rackRate;
    @XmlElement(required = true)
    protected BigDecimal netRate;
    @XmlElement(required = true)
    protected BigDecimal totalDiscount;
    @XmlElement(required = true)
    protected BigDecimal totalLoading;
    @XmlElement(required = true)
    protected BigDecimal serviceTax;
    @XmlElement(required = true)
    protected BigDecimal stampDuty;
    @XmlElement(required = true)
    protected BigDecimal netPremium;
    @XmlElement(required = true)
    protected BigDecimal finalRate;
    @XmlElement(required = true)
    protected BigDecimal pmlLimit;
    @XmlElement(required = true)
    protected Messages messages;
    @XmlElement(required = true)
    protected BigDecimal rackAmount;
    @XmlElement(required = true)
    protected BigDecimal basicPremium;
    @XmlElement(required = true)
    protected BigDecimal nilExcessRate;
    @XmlElement(required = true)
    protected BigDecimal nilExcessNetPremium;
    @XmlElement(required = true)
    protected BigDecimal nilExcessTotalPremium;
    @XmlElement(required = true)
    protected BigDecimal nilExcessStampDuty;
    @XmlElement(required = true)
    protected BigDecimal nilExcessNinetyFivePercentPremium;
    @XmlElement(required = true)
    protected BigDecimal nilExcessNinetyFivePercentRate;
    @XmlElement(required = true)
    protected BigDecimal nilExcessFivePercentPremium;
    @XmlElement(required = true)
    protected BigDecimal nilExcessFivePercentRate;
    @XmlElement(required = true)
    protected TaxDetails nilExcessTaxDetails;
    protected InstallmentExcessDetails installmentExcessDetails;
    @XmlElement(required = true)
    protected TaxDetails taxDetails;
    protected BigDecimal targetPremium;
    protected BigDecimal targetRate;
    protected Boolean targetPremiumFlag;
    protected Boolean targetRateFlag;
    protected Boolean loadingFlag;
    protected Boolean discountFlag;
    @XmlElement(name = "PSLFlag")
    protected Boolean pslFlag;
    @XmlElement(name = "PLLFlag")
    protected Boolean pllFlag;
    protected Boolean sumInsuredFlag;
    protected Boolean intermediaryStorageFlag;
    protected Boolean backdationFlag;
    protected Boolean clausesFlag;
    protected Boolean warrantiesFlag;
    protected Boolean excessFlag;
    protected Boolean superDeviationCargoFlag;
    protected Boolean questionnaireMasterFlag;
    @XmlElement(required = true)
    protected BigDecimal excessAmount;
    @XmlElement(required = true)
    protected BigDecimal brokeragePremium;
    @XmlElement(required = true)
    protected BigDecimal customDutySI;
    protected BigDecimal policyRate;
    protected BackdationDetails backdationDetails;
    protected BigDecimal ninetyFivePerPremium;
    protected BigDecimal fivePercentPremium;
    protected BigDecimal ninetyFivePercentRate;
    protected BigDecimal fivePercentRate;
    protected BigDecimal dutyCOverPremium;
    @XmlElement(required = true)
    protected BigDecimal intermediaryStoragePremium;
    @XmlElement(required = true)
    protected BigDecimal intermediaryStorageRate;
    @XmlElement(required = true)
    protected BigDecimal minimumPremium;
    @XmlElement(required = true)
    protected String finalAuthorityRole;
    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String approvaAuthorityStatus;
    protected com.icicilombard.marine.model.WarrantyDetails[] warrantyDetails;
    protected com.icicilombard.marine.model.ExcessDetails[] excessDetails;
    protected com.icicilombard.marine.model.ClauseDetails[] clauseDetails;
    protected com.icicilombard.marine.model.SubCommodityDetails[] subCommodityDetails;
    protected com.icicilombard.marine.model.MarineCoverDetails[] marineCoverDetails;
    @XmlElement(required = true)
    protected com.icicilombard.marine.model.SubProduct[] subProductsResponse;
    protected BigDecimal totalExposurepremium;
    protected BigDecimal totalSalesExposurePremium;
    protected BigDecimal totalPurchaseExposurePremium;
    protected BigDecimal totalExposureRate;
    protected BigDecimal stampDutyRate;
    protected BigDecimal stopNetPremium;
    protected BigDecimal purchaseExposurePremium;
    protected BigDecimal domesticPurchaseExposurePremium;
    protected BigDecimal domesticSalesExposurePremium;
    protected BigDecimal exportSalesExposurePremium;
    protected BigDecimal importPurchaseExposurePremium;
    protected BigDecimal stopTurnOverRate;
    protected BigDecimal totalStopPremium;
    protected String stopPolicyType;
    protected BigDecimal totalBrokeragePremium;
    protected BigDecimal totalSumInsured;
    protected BigDecimal exposureSumInsured;
    protected BigDecimal stopTurnOverRateBfrDisc;
    protected BigDecimal stopTurnOverRateAftrDisc;
    @XmlElement(required = true)
    protected EquationsResponse equationsDetails;

    /**
     * Gets the value of the uwLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getUwLevel() {
        return uwLevel;
    }

    /**
     * Sets the value of the uwLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUwLevel(Integer value) {
        this.uwLevel = value;
    }

    /**
     * Gets the value of the approverAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproverAuthority() {
        return approverAuthority;
    }

    /**
     * Sets the value of the approverAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproverAuthority(String value) {
        this.approverAuthority = value;
    }

    /**
     * Gets the value of the totalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPremium() {
        return totalPremium;
    }

    /**
     * Sets the value of the totalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPremium(BigDecimal value) {
        this.totalPremium = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRequestID(Object value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the policyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyStatus() {
        return policyStatus;
    }

    /**
     * Sets the value of the policyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyStatus(String value) {
        this.policyStatus = value;
    }

    /**
     * Gets the value of the basicRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicRate() {
        return basicRate;
    }

    /**
     * Sets the value of the basicRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicRate(BigDecimal value) {
        this.basicRate = value;
    }

    /**
     * Gets the value of the rackRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRackRate() {
        return rackRate;
    }

    /**
     * Sets the value of the rackRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRackRate(BigDecimal value) {
        this.rackRate = value;
    }

    /**
     * Gets the value of the netRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetRate() {
        return netRate;
    }

    /**
     * Sets the value of the netRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetRate(BigDecimal value) {
        this.netRate = value;
    }

    /**
     * Gets the value of the totalDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    /**
     * Sets the value of the totalDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDiscount(BigDecimal value) {
        this.totalDiscount = value;
    }

    /**
     * Gets the value of the totalLoading property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalLoading() {
        return totalLoading;
    }

    /**
     * Sets the value of the totalLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalLoading(BigDecimal value) {
        this.totalLoading = value;
    }

    /**
     * Gets the value of the serviceTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceTax() {
        return serviceTax;
    }

    /**
     * Sets the value of the serviceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceTax(BigDecimal value) {
        this.serviceTax = value;
    }

    /**
     * Gets the value of the stampDuty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStampDuty() {
        return stampDuty;
    }

    /**
     * Sets the value of the stampDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStampDuty(BigDecimal value) {
        this.stampDuty = value;
    }

    /**
     * Gets the value of the netPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPremium() {
        return netPremium;
    }

    /**
     * Sets the value of the netPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPremium(BigDecimal value) {
        this.netPremium = value;
    }

    /**
     * Gets the value of the finalRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalRate() {
        return finalRate;
    }

    /**
     * Sets the value of the finalRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalRate(BigDecimal value) {
        this.finalRate = value;
    }

    /**
     * Gets the value of the pmlLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPmlLimit() {
        return pmlLimit;
    }

    /**
     * Sets the value of the pmlLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPmlLimit(BigDecimal value) {
        this.pmlLimit = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link Messages }
     *     
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Messages }
     *     
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the rackAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRackAmount() {
        return rackAmount;
    }

    /**
     * Sets the value of the rackAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRackAmount(BigDecimal value) {
        this.rackAmount = value;
    }

    /**
     * Gets the value of the basicPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicPremium() {
        return basicPremium;
    }

    /**
     * Sets the value of the basicPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicPremium(BigDecimal value) {
        this.basicPremium = value;
    }

    /**
     * Gets the value of the nilExcessRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessRate() {
        return nilExcessRate;
    }

    /**
     * Sets the value of the nilExcessRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessRate(BigDecimal value) {
        this.nilExcessRate = value;
    }

    /**
     * Gets the value of the nilExcessNetPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessNetPremium() {
        return nilExcessNetPremium;
    }

    /**
     * Sets the value of the nilExcessNetPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessNetPremium(BigDecimal value) {
        this.nilExcessNetPremium = value;
    }

    /**
     * Gets the value of the nilExcessTotalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessTotalPremium() {
        return nilExcessTotalPremium;
    }

    /**
     * Sets the value of the nilExcessTotalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessTotalPremium(BigDecimal value) {
        this.nilExcessTotalPremium = value;
    }

    /**
     * Gets the value of the nilExcessStampDuty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessStampDuty() {
        return nilExcessStampDuty;
    }

    /**
     * Sets the value of the nilExcessStampDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessStampDuty(BigDecimal value) {
        this.nilExcessStampDuty = value;
    }

    /**
     * Gets the value of the nilExcessNinetyFivePercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessNinetyFivePercentPremium() {
        return nilExcessNinetyFivePercentPremium;
    }

    /**
     * Sets the value of the nilExcessNinetyFivePercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessNinetyFivePercentPremium(BigDecimal value) {
        this.nilExcessNinetyFivePercentPremium = value;
    }

    /**
     * Gets the value of the nilExcessNinetyFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessNinetyFivePercentRate() {
        return nilExcessNinetyFivePercentRate;
    }

    /**
     * Sets the value of the nilExcessNinetyFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessNinetyFivePercentRate(BigDecimal value) {
        this.nilExcessNinetyFivePercentRate = value;
    }

    /**
     * Gets the value of the nilExcessFivePercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessFivePercentPremium() {
        return nilExcessFivePercentPremium;
    }

    /**
     * Sets the value of the nilExcessFivePercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessFivePercentPremium(BigDecimal value) {
        this.nilExcessFivePercentPremium = value;
    }

    /**
     * Gets the value of the nilExcessFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNilExcessFivePercentRate() {
        return nilExcessFivePercentRate;
    }

    /**
     * Sets the value of the nilExcessFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNilExcessFivePercentRate(BigDecimal value) {
        this.nilExcessFivePercentRate = value;
    }

    /**
     * Gets the value of the nilExcessTaxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetails }
     *     
     */
    public TaxDetails getNilExcessTaxDetails() {
        return nilExcessTaxDetails;
    }

    /**
     * Sets the value of the nilExcessTaxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetails }
     *     
     */
    public void setNilExcessTaxDetails(TaxDetails value) {
        this.nilExcessTaxDetails = value;
    }

    /**
     * Gets the value of the installmentExcessDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentExcessDetails }
     *     
     */
    public InstallmentExcessDetails getInstallmentExcessDetails() {
        return installmentExcessDetails;
    }

    /**
     * Sets the value of the installmentExcessDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentExcessDetails }
     *     
     */
    public void setInstallmentExcessDetails(InstallmentExcessDetails value) {
        this.installmentExcessDetails = value;
    }

    /**
     * Gets the value of the taxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetails }
     *     
     */
    public TaxDetails getTaxDetails() {
        return taxDetails;
    }

    /**
     * Sets the value of the taxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetails }
     *     
     */
    public void setTaxDetails(TaxDetails value) {
        this.taxDetails = value;
    }

    /**
     * Gets the value of the targetPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetPremium() {
        return targetPremium;
    }

    /**
     * Sets the value of the targetPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetPremium(BigDecimal value) {
        this.targetPremium = value;
    }

    /**
     * Gets the value of the targetRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetRate() {
        return targetRate;
    }

    /**
     * Sets the value of the targetRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetRate(BigDecimal value) {
        this.targetRate = value;
    }

    /**
     * Gets the value of the targetPremiumFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetPremiumFlag() {
        return targetPremiumFlag;
    }

    /**
     * Sets the value of the targetPremiumFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetPremiumFlag(Boolean value) {
        this.targetPremiumFlag = value;
    }

    /**
     * Gets the value of the targetRateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetRateFlag() {
        return targetRateFlag;
    }

    /**
     * Sets the value of the targetRateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetRateFlag(Boolean value) {
        this.targetRateFlag = value;
    }

    /**
     * Gets the value of the loadingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoadingFlag() {
        return loadingFlag;
    }

    /**
     * Sets the value of the loadingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadingFlag(Boolean value) {
        this.loadingFlag = value;
    }

    /**
     * Gets the value of the discountFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiscountFlag() {
        return discountFlag;
    }

    /**
     * Sets the value of the discountFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiscountFlag(Boolean value) {
        this.discountFlag = value;
    }

    /**
     * Gets the value of the pslFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPSLFlag() {
        return pslFlag;
    }

    /**
     * Sets the value of the pslFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPSLFlag(Boolean value) {
        this.pslFlag = value;
    }

    /**
     * Gets the value of the pllFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPLLFlag() {
        return pllFlag;
    }

    /**
     * Sets the value of the pllFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPLLFlag(Boolean value) {
        this.pllFlag = value;
    }

    /**
     * Gets the value of the sumInsuredFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSumInsuredFlag() {
        return sumInsuredFlag;
    }

    /**
     * Sets the value of the sumInsuredFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSumInsuredFlag(Boolean value) {
        this.sumInsuredFlag = value;
    }

    /**
     * Gets the value of the intermediaryStorageFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntermediaryStorageFlag() {
        return intermediaryStorageFlag;
    }

    /**
     * Sets the value of the intermediaryStorageFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntermediaryStorageFlag(Boolean value) {
        this.intermediaryStorageFlag = value;
    }

    /**
     * Gets the value of the backdationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackdationFlag() {
        return backdationFlag;
    }

    /**
     * Sets the value of the backdationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackdationFlag(Boolean value) {
        this.backdationFlag = value;
    }

    /**
     * Gets the value of the clausesFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClausesFlag() {
        return clausesFlag;
    }

    /**
     * Sets the value of the clausesFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClausesFlag(Boolean value) {
        this.clausesFlag = value;
    }

    /**
     * Gets the value of the warrantiesFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWarrantiesFlag() {
        return warrantiesFlag;
    }

    /**
     * Sets the value of the warrantiesFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWarrantiesFlag(Boolean value) {
        this.warrantiesFlag = value;
    }

    /**
     * Gets the value of the excessFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcessFlag() {
        return excessFlag;
    }

    /**
     * Sets the value of the excessFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcessFlag(Boolean value) {
        this.excessFlag = value;
    }

    /**
     * Gets the value of the superDeviationCargoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuperDeviationCargoFlag() {
        return superDeviationCargoFlag;
    }

    /**
     * Sets the value of the superDeviationCargoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuperDeviationCargoFlag(Boolean value) {
        this.superDeviationCargoFlag = value;
    }

    /**
     * Gets the value of the questionnaireMasterFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isQuestionnaireMasterFlag() {
        return questionnaireMasterFlag;
    }

    /**
     * Sets the value of the questionnaireMasterFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQuestionnaireMasterFlag(Boolean value) {
        this.questionnaireMasterFlag = value;
    }

    /**
     * Gets the value of the excessAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessAmount() {
        return excessAmount;
    }

    /**
     * Sets the value of the excessAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessAmount(BigDecimal value) {
        this.excessAmount = value;
    }

    /**
     * Gets the value of the brokeragePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBrokeragePremium() {
        return brokeragePremium;
    }

    /**
     * Sets the value of the brokeragePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBrokeragePremium(BigDecimal value) {
        this.brokeragePremium = value;
    }

    /**
     * Gets the value of the customDutySI property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomDutySI() {
        return customDutySI;
    }

    /**
     * Sets the value of the customDutySI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomDutySI(BigDecimal value) {
        this.customDutySI = value;
    }

    /**
     * Gets the value of the policyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPolicyRate() {
        return policyRate;
    }

    /**
     * Sets the value of the policyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPolicyRate(BigDecimal value) {
        this.policyRate = value;
    }

    /**
     * Gets the value of the backdationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BackdationDetails }
     *     
     */
    public BackdationDetails getBackdationDetails() {
        return backdationDetails;
    }

    /**
     * Sets the value of the backdationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackdationDetails }
     *     
     */
    public void setBackdationDetails(BackdationDetails value) {
        this.backdationDetails = value;
    }

    /**
     * Gets the value of the ninetyFivePerPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNinetyFivePerPremium() {
        return ninetyFivePerPremium;
    }

    /**
     * Sets the value of the ninetyFivePerPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNinetyFivePerPremium(BigDecimal value) {
        this.ninetyFivePerPremium = value;
    }

    /**
     * Gets the value of the fivePercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFivePercentPremium() {
        return fivePercentPremium;
    }

    /**
     * Sets the value of the fivePercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFivePercentPremium(BigDecimal value) {
        this.fivePercentPremium = value;
    }

    /**
     * Gets the value of the ninetyFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNinetyFivePercentRate() {
        return ninetyFivePercentRate;
    }

    /**
     * Sets the value of the ninetyFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNinetyFivePercentRate(BigDecimal value) {
        this.ninetyFivePercentRate = value;
    }

    /**
     * Gets the value of the fivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFivePercentRate() {
        return fivePercentRate;
    }

    /**
     * Sets the value of the fivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFivePercentRate(BigDecimal value) {
        this.fivePercentRate = value;
    }

    /**
     * Gets the value of the dutyCOverPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDutyCOverPremium() {
        return dutyCOverPremium;
    }

    /**
     * Sets the value of the dutyCOverPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDutyCOverPremium(BigDecimal value) {
        this.dutyCOverPremium = value;
    }

    /**
     * Gets the value of the intermediaryStoragePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntermediaryStoragePremium() {
        return intermediaryStoragePremium;
    }

    /**
     * Sets the value of the intermediaryStoragePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntermediaryStoragePremium(BigDecimal value) {
        this.intermediaryStoragePremium = value;
    }

    /**
     * Gets the value of the intermediaryStorageRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntermediaryStorageRate() {
        return intermediaryStorageRate;
    }

    /**
     * Sets the value of the intermediaryStorageRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntermediaryStorageRate(BigDecimal value) {
        this.intermediaryStorageRate = value;
    }

    /**
     * Gets the value of the minimumPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumPremium() {
        return minimumPremium;
    }

    /**
     * Sets the value of the minimumPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumPremium(BigDecimal value) {
        this.minimumPremium = value;
    }

    /**
     * Gets the value of the finalAuthorityRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalAuthorityRole() {
        return finalAuthorityRole;
    }

    /**
     * Sets the value of the finalAuthorityRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalAuthorityRole(String value) {
        this.finalAuthorityRole = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the approvaAuthorityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovaAuthorityStatus() {
        return approvaAuthorityStatus;
    }

    /**
     * Sets the value of the approvaAuthorityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovaAuthorityStatus(String value) {
        this.approvaAuthorityStatus = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.WarrantyDetails }
     *     
     */
    public com.icicilombard.marine.model.WarrantyDetails[] getWarrantyDetails() {
        if (this.warrantyDetails == null) {
            return new com.icicilombard.marine.model.WarrantyDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.WarrantyDetails[] retVal = new com.icicilombard.marine.model.WarrantyDetails[this.warrantyDetails.length] ;
        System.arraycopy(this.warrantyDetails, 0, retVal, 0, this.warrantyDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.WarrantyDetails }
     *     
     */
    public com.icicilombard.marine.model.WarrantyDetails getWarrantyDetails(int idx) {
        if (this.warrantyDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.warrantyDetails[idx];
    }

    public int getWarrantyDetailsLength() {
        if (this.warrantyDetails == null) {
            return  0;
        }
        return this.warrantyDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.WarrantyDetails }
     *     
     */
    public void setWarrantyDetails(com.icicilombard.marine.model.WarrantyDetails[] values) {
        int len = values.length;
        this.warrantyDetails = ((com.icicilombard.marine.model.WarrantyDetails[]) new com.icicilombard.marine.model.WarrantyDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.warrantyDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.WarrantyDetails }
     *     
     */
    public com.icicilombard.marine.model.WarrantyDetails setWarrantyDetails(int idx, com.icicilombard.marine.model.WarrantyDetails value) {
        return this.warrantyDetails[idx] = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.ExcessDetails }
     *     
     */
    public com.icicilombard.marine.model.ExcessDetails[] getExcessDetails() {
        if (this.excessDetails == null) {
            return new com.icicilombard.marine.model.ExcessDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.ExcessDetails[] retVal = new com.icicilombard.marine.model.ExcessDetails[this.excessDetails.length] ;
        System.arraycopy(this.excessDetails, 0, retVal, 0, this.excessDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.ExcessDetails }
     *     
     */
    public com.icicilombard.marine.model.ExcessDetails getExcessDetails(int idx) {
        if (this.excessDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.excessDetails[idx];
    }

    public int getExcessDetailsLength() {
        if (this.excessDetails == null) {
            return  0;
        }
        return this.excessDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.ExcessDetails }
     *     
     */
    public void setExcessDetails(com.icicilombard.marine.model.ExcessDetails[] values) {
        int len = values.length;
        this.excessDetails = ((com.icicilombard.marine.model.ExcessDetails[]) new com.icicilombard.marine.model.ExcessDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.excessDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.ExcessDetails }
     *     
     */
    public com.icicilombard.marine.model.ExcessDetails setExcessDetails(int idx, com.icicilombard.marine.model.ExcessDetails value) {
        return this.excessDetails[idx] = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.ClauseDetails }
     *     
     */
    public com.icicilombard.marine.model.ClauseDetails[] getClauseDetails() {
        if (this.clauseDetails == null) {
            return new com.icicilombard.marine.model.ClauseDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.ClauseDetails[] retVal = new com.icicilombard.marine.model.ClauseDetails[this.clauseDetails.length] ;
        System.arraycopy(this.clauseDetails, 0, retVal, 0, this.clauseDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.ClauseDetails }
     *     
     */
    public com.icicilombard.marine.model.ClauseDetails getClauseDetails(int idx) {
        if (this.clauseDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.clauseDetails[idx];
    }

    public int getClauseDetailsLength() {
        if (this.clauseDetails == null) {
            return  0;
        }
        return this.clauseDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.ClauseDetails }
     *     
     */
    public void setClauseDetails(com.icicilombard.marine.model.ClauseDetails[] values) {
        int len = values.length;
        this.clauseDetails = ((com.icicilombard.marine.model.ClauseDetails[]) new com.icicilombard.marine.model.ClauseDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.clauseDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.ClauseDetails }
     *     
     */
    public com.icicilombard.marine.model.ClauseDetails setClauseDetails(int idx, com.icicilombard.marine.model.ClauseDetails value) {
        return this.clauseDetails[idx] = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.SubCommodityDetails }
     *     
     */
    public com.icicilombard.marine.model.SubCommodityDetails[] getSubCommodityDetails() {
        if (this.subCommodityDetails == null) {
            return new com.icicilombard.marine.model.SubCommodityDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.SubCommodityDetails[] retVal = new com.icicilombard.marine.model.SubCommodityDetails[this.subCommodityDetails.length] ;
        System.arraycopy(this.subCommodityDetails, 0, retVal, 0, this.subCommodityDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.SubCommodityDetails }
     *     
     */
    public com.icicilombard.marine.model.SubCommodityDetails getSubCommodityDetails(int idx) {
        if (this.subCommodityDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.subCommodityDetails[idx];
    }

    public int getSubCommodityDetailsLength() {
        if (this.subCommodityDetails == null) {
            return  0;
        }
        return this.subCommodityDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.SubCommodityDetails }
     *     
     */
    public void setSubCommodityDetails(com.icicilombard.marine.model.SubCommodityDetails[] values) {
        int len = values.length;
        this.subCommodityDetails = ((com.icicilombard.marine.model.SubCommodityDetails[]) new com.icicilombard.marine.model.SubCommodityDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.subCommodityDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.SubCommodityDetails }
     *     
     */
    public com.icicilombard.marine.model.SubCommodityDetails setSubCommodityDetails(int idx, com.icicilombard.marine.model.SubCommodityDetails value) {
        return this.subCommodityDetails[idx] = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.MarineCoverDetails }
     *     
     */
    public com.icicilombard.marine.model.MarineCoverDetails[] getMarineCoverDetails() {
        if (this.marineCoverDetails == null) {
            return new com.icicilombard.marine.model.MarineCoverDetails[ 0 ] ;
        }
        com.icicilombard.marine.model.MarineCoverDetails[] retVal = new com.icicilombard.marine.model.MarineCoverDetails[this.marineCoverDetails.length] ;
        System.arraycopy(this.marineCoverDetails, 0, retVal, 0, this.marineCoverDetails.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.MarineCoverDetails }
     *     
     */
    public com.icicilombard.marine.model.MarineCoverDetails getMarineCoverDetails(int idx) {
        if (this.marineCoverDetails == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.marineCoverDetails[idx];
    }

    public int getMarineCoverDetailsLength() {
        if (this.marineCoverDetails == null) {
            return  0;
        }
        return this.marineCoverDetails.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.MarineCoverDetails }
     *     
     */
    public void setMarineCoverDetails(com.icicilombard.marine.model.MarineCoverDetails[] values) {
        int len = values.length;
        this.marineCoverDetails = ((com.icicilombard.marine.model.MarineCoverDetails[]) new com.icicilombard.marine.model.MarineCoverDetails[len] );
        for (int i = 0; (i<len); i ++) {
            this.marineCoverDetails[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.MarineCoverDetails }
     *     
     */
    public com.icicilombard.marine.model.MarineCoverDetails setMarineCoverDetails(int idx, com.icicilombard.marine.model.MarineCoverDetails value) {
        return this.marineCoverDetails[idx] = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct[] getSubProductsResponse() {
        if (this.subProductsResponse == null) {
            return new com.icicilombard.marine.model.SubProduct[ 0 ] ;
        }
        com.icicilombard.marine.model.SubProduct[] retVal = new com.icicilombard.marine.model.SubProduct[this.subProductsResponse.length] ;
        System.arraycopy(this.subProductsResponse, 0, retVal, 0, this.subProductsResponse.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct getSubProductsResponse(int idx) {
        if (this.subProductsResponse == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.subProductsResponse[idx];
    }

    public int getSubProductsResponseLength() {
        if (this.subProductsResponse == null) {
            return  0;
        }
        return this.subProductsResponse.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public void setSubProductsResponse(com.icicilombard.marine.model.SubProduct[] values) {
        int len = values.length;
        this.subProductsResponse = ((com.icicilombard.marine.model.SubProduct[]) new com.icicilombard.marine.model.SubProduct[len] );
        for (int i = 0; (i<len); i ++) {
            this.subProductsResponse[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct setSubProductsResponse(int idx, com.icicilombard.marine.model.SubProduct value) {
        return this.subProductsResponse[idx] = value;
    }

    /**
     * Gets the value of the totalExposurepremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalExposurepremium() {
        return totalExposurepremium;
    }

    /**
     * Sets the value of the totalExposurepremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalExposurepremium(BigDecimal value) {
        this.totalExposurepremium = value;
    }

    /**
     * Gets the value of the totalSalesExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSalesExposurePremium() {
        return totalSalesExposurePremium;
    }

    /**
     * Sets the value of the totalSalesExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSalesExposurePremium(BigDecimal value) {
        this.totalSalesExposurePremium = value;
    }

    /**
     * Gets the value of the totalPurchaseExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPurchaseExposurePremium() {
        return totalPurchaseExposurePremium;
    }

    /**
     * Sets the value of the totalPurchaseExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPurchaseExposurePremium(BigDecimal value) {
        this.totalPurchaseExposurePremium = value;
    }

    /**
     * Gets the value of the totalExposureRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalExposureRate() {
        return totalExposureRate;
    }

    /**
     * Sets the value of the totalExposureRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalExposureRate(BigDecimal value) {
        this.totalExposureRate = value;
    }

    /**
     * Gets the value of the stampDutyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStampDutyRate() {
        return stampDutyRate;
    }

    /**
     * Sets the value of the stampDutyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStampDutyRate(BigDecimal value) {
        this.stampDutyRate = value;
    }

    /**
     * Gets the value of the stopNetPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStopNetPremium() {
        return stopNetPremium;
    }

    /**
     * Sets the value of the stopNetPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStopNetPremium(BigDecimal value) {
        this.stopNetPremium = value;
    }

    /**
     * Gets the value of the purchaseExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPurchaseExposurePremium() {
        return purchaseExposurePremium;
    }

    /**
     * Sets the value of the purchaseExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPurchaseExposurePremium(BigDecimal value) {
        this.purchaseExposurePremium = value;
    }

    /**
     * Gets the value of the domesticPurchaseExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDomesticPurchaseExposurePremium() {
        return domesticPurchaseExposurePremium;
    }

    /**
     * Sets the value of the domesticPurchaseExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDomesticPurchaseExposurePremium(BigDecimal value) {
        this.domesticPurchaseExposurePremium = value;
    }

    /**
     * Gets the value of the domesticSalesExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDomesticSalesExposurePremium() {
        return domesticSalesExposurePremium;
    }

    /**
     * Sets the value of the domesticSalesExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDomesticSalesExposurePremium(BigDecimal value) {
        this.domesticSalesExposurePremium = value;
    }

    /**
     * Gets the value of the exportSalesExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExportSalesExposurePremium() {
        return exportSalesExposurePremium;
    }

    /**
     * Sets the value of the exportSalesExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExportSalesExposurePremium(BigDecimal value) {
        this.exportSalesExposurePremium = value;
    }

    /**
     * Gets the value of the importPurchaseExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportPurchaseExposurePremium() {
        return importPurchaseExposurePremium;
    }

    /**
     * Sets the value of the importPurchaseExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportPurchaseExposurePremium(BigDecimal value) {
        this.importPurchaseExposurePremium = value;
    }

    /**
     * Gets the value of the stopTurnOverRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStopTurnOverRate() {
        return stopTurnOverRate;
    }

    /**
     * Sets the value of the stopTurnOverRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStopTurnOverRate(BigDecimal value) {
        this.stopTurnOverRate = value;
    }

    /**
     * Gets the value of the totalStopPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalStopPremium() {
        return totalStopPremium;
    }

    /**
     * Sets the value of the totalStopPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalStopPremium(BigDecimal value) {
        this.totalStopPremium = value;
    }

    /**
     * Gets the value of the stopPolicyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopPolicyType() {
        return stopPolicyType;
    }

    /**
     * Sets the value of the stopPolicyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopPolicyType(String value) {
        this.stopPolicyType = value;
    }

    /**
     * Gets the value of the totalBrokeragePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalBrokeragePremium() {
        return totalBrokeragePremium;
    }

    /**
     * Sets the value of the totalBrokeragePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalBrokeragePremium(BigDecimal value) {
        this.totalBrokeragePremium = value;
    }

    /**
     * Gets the value of the totalSumInsured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSumInsured() {
        return totalSumInsured;
    }

    /**
     * Sets the value of the totalSumInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSumInsured(BigDecimal value) {
        this.totalSumInsured = value;
    }

    /**
     * Gets the value of the exposureSumInsured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExposureSumInsured() {
        return exposureSumInsured;
    }

    /**
     * Sets the value of the exposureSumInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExposureSumInsured(BigDecimal value) {
        this.exposureSumInsured = value;
    }

    /**
     * Gets the value of the stopTurnOverRateBfrDisc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStopTurnOverRateBfrDisc() {
        return stopTurnOverRateBfrDisc;
    }

    /**
     * Sets the value of the stopTurnOverRateBfrDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStopTurnOverRateBfrDisc(BigDecimal value) {
        this.stopTurnOverRateBfrDisc = value;
    }

    /**
     * Gets the value of the stopTurnOverRateAftrDisc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStopTurnOverRateAftrDisc() {
        return stopTurnOverRateAftrDisc;
    }

    /**
     * Sets the value of the stopTurnOverRateAftrDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStopTurnOverRateAftrDisc(BigDecimal value) {
        this.stopTurnOverRateAftrDisc = value;
    }

    /**
     * Gets the value of the equationsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EquationsResponse }
     *     
     */
    public EquationsResponse getEquationsDetails() {
        return equationsDetails;
    }

    /**
     * Sets the value of the equationsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquationsResponse }
     *     
     */
    public void setEquationsDetails(EquationsResponse value) {
        this.equationsDetails = value;
    }

}
