//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.icicilombard.marine.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MarineResponse_QNAME = new QName("http://marine.icicilombard.com", "MarineResponse");
    private final static QName _MarineRequest_QNAME = new QName("http://marine.icicilombard.com", "marineRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.icicilombard.marine.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MarineResponse }
     * 
     */
    public MarineResponse createMarineResponse() {
        return new MarineResponse();
    }

    /**
     * Create an instance of {@link CancellationCharges }
     * 
     */
    public CancellationCharges createCancellationCharges() {
        return new CancellationCharges();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link EquationsResponse }
     * 
     */
    public EquationsResponse createEquationsResponse() {
        return new EquationsResponse();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link MarineCoverDetails }
     * 
     */
    public MarineCoverDetails createMarineCoverDetails() {
        return new MarineCoverDetails();
    }

    /**
     * Create an instance of {@link ExceptionalScenarios }
     * 
     */
    public ExceptionalScenarios createExceptionalScenarios() {
        return new ExceptionalScenarios();
    }

    /**
     * Create an instance of {@link ServiceTaxDetails }
     * 
     */
    public ServiceTaxDetails createServiceTaxDetails() {
        return new ServiceTaxDetails();
    }

    /**
     * Create an instance of {@link InstallmentExcessDetails }
     * 
     */
    public InstallmentExcessDetails createInstallmentExcessDetails() {
        return new InstallmentExcessDetails();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link BackdationDetails }
     * 
     */
    public BackdationDetails createBackdationDetails() {
        return new BackdationDetails();
    }

    /**
     * Create an instance of {@link SubCommodityDetails }
     * 
     */
    public SubCommodityDetails createSubCommodityDetails() {
        return new SubCommodityDetails();
    }

    /**
     * Create an instance of {@link WarrantyDetails }
     * 
     */
    public WarrantyDetails createWarrantyDetails() {
        return new WarrantyDetails();
    }

    /**
     * Create an instance of {@link EndorsementInfo }
     * 
     */
    public EndorsementInfo createEndorsementInfo() {
        return new EndorsementInfo();
    }

    /**
     * Create an instance of {@link SubProduct }
     * 
     */
    public SubProduct createSubProduct() {
        return new SubProduct();
    }

    /**
     * Create an instance of {@link GSTTotalDetails }
     * 
     */
    public GSTTotalDetails createGSTTotalDetails() {
        return new GSTTotalDetails();
    }

    /**
     * Create an instance of {@link UserRoles }
     * 
     */
    public UserRoles createUserRoles() {
        return new UserRoles();
    }

    /**
     * Create an instance of {@link ClauseDetails }
     * 
     */
    public ClauseDetails createClauseDetails() {
        return new ClauseDetails();
    }

    /**
     * Create an instance of {@link InstallmentDetails }
     * 
     */
    public InstallmentDetails createInstallmentDetails() {
        return new InstallmentDetails();
    }

    /**
     * Create an instance of {@link GSTServiceDetails }
     * 
     */
    public GSTServiceDetails createGSTServiceDetails() {
        return new GSTServiceDetails();
    }

    /**
     * Create an instance of {@link TaxDetails }
     * 
     */
    public TaxDetails createTaxDetails() {
        return new TaxDetails();
    }

    /**
     * Create an instance of {@link ExcessDetails }
     * 
     */
    public ExcessDetails createExcessDetails() {
        return new ExcessDetails();
    }

    /**
     * Create an instance of {@link MarineRequest }
     * 
     */
    public MarineRequest createMarineRequest() {
        return new MarineRequest();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link StampDuty }
     * 
     */
    public StampDuty createStampDuty() {
        return new StampDuty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarineResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marine.icicilombard.com", name = "MarineResponse")
    public JAXBElement<MarineResponse> createMarineResponse(MarineResponse value) {
        return new JAXBElement<MarineResponse>(_MarineResponse_QNAME, MarineResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarineRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marine.icicilombard.com", name = "marineRequest")
    public JAXBElement<MarineRequest> createMarineRequest(MarineRequest value) {
        return new JAXBElement<MarineRequest>(_MarineRequest_QNAME, MarineRequest.class, null, value);
    }

}
