//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paramterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterType" type="{http://marine.icicilombard.com}ParameterType"/>
 *         &lt;element name="relativity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="weightage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="parameterValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {
    "paramterName",
    "parameterType",
    "relativity",
    "weightage",
    "parameterValue"
})
public class Parameters
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected String paramterName;
    @XmlElement(required = true)
    protected ParameterType parameterType;
    @XmlElement(required = true)
    protected BigDecimal relativity;
    @XmlElement(required = true)
    protected BigDecimal weightage;
    @XmlElement(required = true)
    protected String parameterValue;

    /**
     * Gets the value of the paramterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamterName() {
        return paramterName;
    }

    /**
     * Sets the value of the paramterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamterName(String value) {
        this.paramterName = value;
    }

    /**
     * Gets the value of the parameterType property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterType }
     *     
     */
    public ParameterType getParameterType() {
        return parameterType;
    }

    /**
     * Sets the value of the parameterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterType }
     *     
     */
    public void setParameterType(ParameterType value) {
        this.parameterType = value;
    }

    /**
     * Gets the value of the relativity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelativity() {
        return relativity;
    }

    /**
     * Sets the value of the relativity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelativity(BigDecimal value) {
        this.relativity = value;
    }

    /**
     * Gets the value of the weightage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightage() {
        return weightage;
    }

    /**
     * Sets the value of the weightage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightage(BigDecimal value) {
        this.weightage = value;
    }

    /**
     * Gets the value of the parameterValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterValue() {
        return parameterValue;
    }

    /**
     * Sets the value of the parameterValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterValue(String value) {
        this.parameterValue = value;
    }

}
