//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CMCCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subcommodityCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subProducts" type="{http://marine.icicilombard.com}SubProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loading" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="sumInsured" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="typeOfSubCargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rackRateInPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="excessOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brokeragePercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="typeOfCargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="perSendingLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="perLocationLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="modeOfConveyance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consignmentValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="serviceTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="excessPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="customDutySI" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="riInwardFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commodityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="targetRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="targetPremiumFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="targetRateFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="loadingFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="discountFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PSLFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PLLFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="sumInsuredFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="intermediaryStorageFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="backdationFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="clausesFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="warrantiesFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="excessFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "productCode",
    "cmcCode",
    "subcommodityCode",
    "subProducts",
    "loading",
    "discount",
    "sumInsured",
    "typeOfSubCargo",
    "rackRateInPercentage",
    "excessOption",
    "brokeragePercentage",
    "typeOfCargo",
    "perSendingLimit",
    "perLocationLimit",
    "modeOfConveyance",
    "consignmentValue",
    "serviceTax",
    "excessPercentage",
    "customDutySI",
    "riInwardFlag",
    "coverageType",
    "commodityName",
    "agentID",
    "targetPremium",
    "targetRate",
    "targetPremiumFlag",
    "targetRateFlag",
    "loadingFlag",
    "discountFlag",
    "pslFlag",
    "pllFlag",
    "sumInsuredFlag",
    "intermediaryStorageFlag",
    "backdationFlag",
    "clausesFlag",
    "warrantiesFlag",
    "excessFlag"
})
public class Product
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected String productCode;
    @XmlElement(name = "CMCCode")
    protected String cmcCode;
    protected String subcommodityCode;
    protected com.icicilombard.marine.model.SubProduct[] subProducts;
    protected BigDecimal loading;
    protected BigDecimal discount;
    @XmlElement(required = true)
    protected BigDecimal sumInsured;
    @XmlElement(required = true)
    protected String typeOfSubCargo;
    @XmlElement(required = true)
    protected BigDecimal rackRateInPercentage;
    @XmlElement(required = true)
    protected String excessOption;
    protected BigDecimal brokeragePercentage;
    @XmlElement(required = true)
    protected String typeOfCargo;
    @XmlElement(required = true)
    protected BigDecimal perSendingLimit;
    @XmlElement(required = true)
    protected BigDecimal perLocationLimit;
    @XmlElement(required = true)
    protected String modeOfConveyance;
    protected BigDecimal consignmentValue;
    protected BigDecimal serviceTax;
    @XmlElement(required = true)
    protected BigDecimal excessPercentage;
    protected BigDecimal customDutySI;
    @XmlElement(required = true)
    protected String riInwardFlag;
    protected String coverageType;
    protected String commodityName;
    protected String agentID;
    protected BigDecimal targetPremium;
    protected BigDecimal targetRate;
    protected Boolean targetPremiumFlag;
    protected Boolean targetRateFlag;
    protected Boolean loadingFlag;
    protected Boolean discountFlag;
    @XmlElement(name = "PSLFlag")
    protected Boolean pslFlag;
    @XmlElement(name = "PLLFlag")
    protected Boolean pllFlag;
    protected Boolean sumInsuredFlag;
    protected Boolean intermediaryStorageFlag;
    protected Boolean backdationFlag;
    protected Boolean clausesFlag;
    protected Boolean warrantiesFlag;
    protected Boolean excessFlag;

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the cmcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMCCode() {
        return cmcCode;
    }

    /**
     * Sets the value of the cmcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMCCode(String value) {
        this.cmcCode = value;
    }

    /**
     * Gets the value of the subcommodityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcommodityCode() {
        return subcommodityCode;
    }

    /**
     * Sets the value of the subcommodityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcommodityCode(String value) {
        this.subcommodityCode = value;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct[] getSubProducts() {
        if (this.subProducts == null) {
            return new com.icicilombard.marine.model.SubProduct[ 0 ] ;
        }
        com.icicilombard.marine.model.SubProduct[] retVal = new com.icicilombard.marine.model.SubProduct[this.subProducts.length] ;
        System.arraycopy(this.subProducts, 0, retVal, 0, this.subProducts.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct getSubProducts(int idx) {
        if (this.subProducts == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.subProducts[idx];
    }

    public int getSubProductsLength() {
        if (this.subProducts == null) {
            return  0;
        }
        return this.subProducts.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public void setSubProducts(com.icicilombard.marine.model.SubProduct[] values) {
        int len = values.length;
        this.subProducts = ((com.icicilombard.marine.model.SubProduct[]) new com.icicilombard.marine.model.SubProduct[len] );
        for (int i = 0; (i<len); i ++) {
            this.subProducts[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link com.icicilombard.marine.model.SubProduct }
     *     
     */
    public com.icicilombard.marine.model.SubProduct setSubProducts(int idx, com.icicilombard.marine.model.SubProduct value) {
        return this.subProducts[idx] = value;
    }

    /**
     * Gets the value of the loading property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoading() {
        return loading;
    }

    /**
     * Sets the value of the loading property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoading(BigDecimal value) {
        this.loading = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscount(BigDecimal value) {
        this.discount = value;
    }

    /**
     * Gets the value of the sumInsured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumInsured() {
        return sumInsured;
    }

    /**
     * Sets the value of the sumInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumInsured(BigDecimal value) {
        this.sumInsured = value;
    }

    /**
     * Gets the value of the typeOfSubCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfSubCargo() {
        return typeOfSubCargo;
    }

    /**
     * Sets the value of the typeOfSubCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfSubCargo(String value) {
        this.typeOfSubCargo = value;
    }

    /**
     * Gets the value of the rackRateInPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRackRateInPercentage() {
        return rackRateInPercentage;
    }

    /**
     * Sets the value of the rackRateInPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRackRateInPercentage(BigDecimal value) {
        this.rackRateInPercentage = value;
    }

    /**
     * Gets the value of the excessOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessOption() {
        return excessOption;
    }

    /**
     * Sets the value of the excessOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessOption(String value) {
        this.excessOption = value;
    }

    /**
     * Gets the value of the brokeragePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBrokeragePercentage() {
        return brokeragePercentage;
    }

    /**
     * Sets the value of the brokeragePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBrokeragePercentage(BigDecimal value) {
        this.brokeragePercentage = value;
    }

    /**
     * Gets the value of the typeOfCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfCargo() {
        return typeOfCargo;
    }

    /**
     * Sets the value of the typeOfCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfCargo(String value) {
        this.typeOfCargo = value;
    }

    /**
     * Gets the value of the perSendingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerSendingLimit() {
        return perSendingLimit;
    }

    /**
     * Sets the value of the perSendingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerSendingLimit(BigDecimal value) {
        this.perSendingLimit = value;
    }

    /**
     * Gets the value of the perLocationLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerLocationLimit() {
        return perLocationLimit;
    }

    /**
     * Sets the value of the perLocationLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerLocationLimit(BigDecimal value) {
        this.perLocationLimit = value;
    }

    /**
     * Gets the value of the modeOfConveyance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeOfConveyance() {
        return modeOfConveyance;
    }

    /**
     * Sets the value of the modeOfConveyance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeOfConveyance(String value) {
        this.modeOfConveyance = value;
    }

    /**
     * Gets the value of the consignmentValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsignmentValue() {
        return consignmentValue;
    }

    /**
     * Sets the value of the consignmentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsignmentValue(BigDecimal value) {
        this.consignmentValue = value;
    }

    /**
     * Gets the value of the serviceTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceTax() {
        return serviceTax;
    }

    /**
     * Sets the value of the serviceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceTax(BigDecimal value) {
        this.serviceTax = value;
    }

    /**
     * Gets the value of the excessPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessPercentage() {
        return excessPercentage;
    }

    /**
     * Sets the value of the excessPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessPercentage(BigDecimal value) {
        this.excessPercentage = value;
    }

    /**
     * Gets the value of the customDutySI property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomDutySI() {
        return customDutySI;
    }

    /**
     * Sets the value of the customDutySI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomDutySI(BigDecimal value) {
        this.customDutySI = value;
    }

    /**
     * Gets the value of the riInwardFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiInwardFlag() {
        return riInwardFlag;
    }

    /**
     * Sets the value of the riInwardFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiInwardFlag(String value) {
        this.riInwardFlag = value;
    }

    /**
     * Gets the value of the coverageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageType() {
        return coverageType;
    }

    /**
     * Sets the value of the coverageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageType(String value) {
        this.coverageType = value;
    }

    /**
     * Gets the value of the commodityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * Sets the value of the commodityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityName(String value) {
        this.commodityName = value;
    }

    /**
     * Gets the value of the agentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentID() {
        return agentID;
    }

    /**
     * Sets the value of the agentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentID(String value) {
        this.agentID = value;
    }

    /**
     * Gets the value of the targetPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetPremium() {
        return targetPremium;
    }

    /**
     * Sets the value of the targetPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetPremium(BigDecimal value) {
        this.targetPremium = value;
    }

    /**
     * Gets the value of the targetRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetRate() {
        return targetRate;
    }

    /**
     * Sets the value of the targetRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetRate(BigDecimal value) {
        this.targetRate = value;
    }

    /**
     * Gets the value of the targetPremiumFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetPremiumFlag() {
        return targetPremiumFlag;
    }

    /**
     * Sets the value of the targetPremiumFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetPremiumFlag(Boolean value) {
        this.targetPremiumFlag = value;
    }

    /**
     * Gets the value of the targetRateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetRateFlag() {
        return targetRateFlag;
    }

    /**
     * Sets the value of the targetRateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetRateFlag(Boolean value) {
        this.targetRateFlag = value;
    }

    /**
     * Gets the value of the loadingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoadingFlag() {
        return loadingFlag;
    }

    /**
     * Sets the value of the loadingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadingFlag(Boolean value) {
        this.loadingFlag = value;
    }

    /**
     * Gets the value of the discountFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiscountFlag() {
        return discountFlag;
    }

    /**
     * Sets the value of the discountFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiscountFlag(Boolean value) {
        this.discountFlag = value;
    }

    /**
     * Gets the value of the pslFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPSLFlag() {
        return pslFlag;
    }

    /**
     * Sets the value of the pslFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPSLFlag(Boolean value) {
        this.pslFlag = value;
    }

    /**
     * Gets the value of the pllFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPLLFlag() {
        return pllFlag;
    }

    /**
     * Sets the value of the pllFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPLLFlag(Boolean value) {
        this.pllFlag = value;
    }

    /**
     * Gets the value of the sumInsuredFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSumInsuredFlag() {
        return sumInsuredFlag;
    }

    /**
     * Sets the value of the sumInsuredFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSumInsuredFlag(Boolean value) {
        this.sumInsuredFlag = value;
    }

    /**
     * Gets the value of the intermediaryStorageFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntermediaryStorageFlag() {
        return intermediaryStorageFlag;
    }

    /**
     * Sets the value of the intermediaryStorageFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntermediaryStorageFlag(Boolean value) {
        this.intermediaryStorageFlag = value;
    }

    /**
     * Gets the value of the backdationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackdationFlag() {
        return backdationFlag;
    }

    /**
     * Sets the value of the backdationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackdationFlag(Boolean value) {
        this.backdationFlag = value;
    }

    /**
     * Gets the value of the clausesFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClausesFlag() {
        return clausesFlag;
    }

    /**
     * Sets the value of the clausesFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClausesFlag(Boolean value) {
        this.clausesFlag = value;
    }

    /**
     * Gets the value of the warrantiesFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWarrantiesFlag() {
        return warrantiesFlag;
    }

    /**
     * Sets the value of the warrantiesFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWarrantiesFlag(Boolean value) {
        this.warrantiesFlag = value;
    }

    /**
     * Gets the value of the excessFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcessFlag() {
        return excessFlag;
    }

    /**
     * Sets the value of the excessFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcessFlag(Boolean value) {
        this.excessFlag = value;
    }

}
