//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTaxDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceTaxDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="basicServiceTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="educationCess" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="higherEducationCess" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="swachhBharatCess" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="krishiKalyanCess" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="salesTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="surcharge" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="basicServiceTaxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="educationCessRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="higherEducationCessRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="swachhBharatCessRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="krishiKalyanCessRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="salesTaxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="surchargeRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalTaxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="premiumAfterTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceTaxDetails", propOrder = {
    "basicServiceTax",
    "educationCess",
    "higherEducationCess",
    "swachhBharatCess",
    "krishiKalyanCess",
    "salesTax",
    "surcharge",
    "totalTax",
    "basicServiceTaxRate",
    "educationCessRate",
    "higherEducationCessRate",
    "swachhBharatCessRate",
    "krishiKalyanCessRate",
    "salesTaxRate",
    "surchargeRate",
    "totalTaxRate",
    "premiumAfterTax"
})
public class ServiceTaxDetails
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected BigDecimal basicServiceTax;
    @XmlElement(required = true)
    protected BigDecimal educationCess;
    @XmlElement(required = true)
    protected BigDecimal higherEducationCess;
    @XmlElement(required = true)
    protected BigDecimal swachhBharatCess;
    @XmlElement(required = true)
    protected BigDecimal krishiKalyanCess;
    @XmlElement(required = true)
    protected BigDecimal salesTax;
    @XmlElement(required = true)
    protected BigDecimal surcharge;
    @XmlElement(required = true)
    protected BigDecimal totalTax;
    @XmlElement(required = true)
    protected BigDecimal basicServiceTaxRate;
    @XmlElement(required = true)
    protected BigDecimal educationCessRate;
    @XmlElement(required = true)
    protected BigDecimal higherEducationCessRate;
    @XmlElement(required = true)
    protected BigDecimal swachhBharatCessRate;
    @XmlElement(required = true)
    protected BigDecimal krishiKalyanCessRate;
    @XmlElement(required = true)
    protected BigDecimal salesTaxRate;
    @XmlElement(required = true)
    protected BigDecimal surchargeRate;
    @XmlElement(required = true)
    protected BigDecimal totalTaxRate;
    @XmlElement(required = true)
    protected BigDecimal premiumAfterTax;

    /**
     * Gets the value of the basicServiceTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicServiceTax() {
        return basicServiceTax;
    }

    /**
     * Sets the value of the basicServiceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicServiceTax(BigDecimal value) {
        this.basicServiceTax = value;
    }

    /**
     * Gets the value of the educationCess property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEducationCess() {
        return educationCess;
    }

    /**
     * Sets the value of the educationCess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEducationCess(BigDecimal value) {
        this.educationCess = value;
    }

    /**
     * Gets the value of the higherEducationCess property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHigherEducationCess() {
        return higherEducationCess;
    }

    /**
     * Sets the value of the higherEducationCess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHigherEducationCess(BigDecimal value) {
        this.higherEducationCess = value;
    }

    /**
     * Gets the value of the swachhBharatCess property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSwachhBharatCess() {
        return swachhBharatCess;
    }

    /**
     * Sets the value of the swachhBharatCess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSwachhBharatCess(BigDecimal value) {
        this.swachhBharatCess = value;
    }

    /**
     * Gets the value of the krishiKalyanCess property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKrishiKalyanCess() {
        return krishiKalyanCess;
    }

    /**
     * Sets the value of the krishiKalyanCess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKrishiKalyanCess(BigDecimal value) {
        this.krishiKalyanCess = value;
    }

    /**
     * Gets the value of the salesTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalesTax() {
        return salesTax;
    }

    /**
     * Sets the value of the salesTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalesTax(BigDecimal value) {
        this.salesTax = value;
    }

    /**
     * Gets the value of the surcharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurcharge() {
        return surcharge;
    }

    /**
     * Sets the value of the surcharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurcharge(BigDecimal value) {
        this.surcharge = value;
    }

    /**
     * Gets the value of the totalTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTax(BigDecimal value) {
        this.totalTax = value;
    }

    /**
     * Gets the value of the basicServiceTaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasicServiceTaxRate() {
        return basicServiceTaxRate;
    }

    /**
     * Sets the value of the basicServiceTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasicServiceTaxRate(BigDecimal value) {
        this.basicServiceTaxRate = value;
    }

    /**
     * Gets the value of the educationCessRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEducationCessRate() {
        return educationCessRate;
    }

    /**
     * Sets the value of the educationCessRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEducationCessRate(BigDecimal value) {
        this.educationCessRate = value;
    }

    /**
     * Gets the value of the higherEducationCessRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHigherEducationCessRate() {
        return higherEducationCessRate;
    }

    /**
     * Sets the value of the higherEducationCessRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHigherEducationCessRate(BigDecimal value) {
        this.higherEducationCessRate = value;
    }

    /**
     * Gets the value of the swachhBharatCessRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSwachhBharatCessRate() {
        return swachhBharatCessRate;
    }

    /**
     * Sets the value of the swachhBharatCessRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSwachhBharatCessRate(BigDecimal value) {
        this.swachhBharatCessRate = value;
    }

    /**
     * Gets the value of the krishiKalyanCessRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKrishiKalyanCessRate() {
        return krishiKalyanCessRate;
    }

    /**
     * Sets the value of the krishiKalyanCessRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKrishiKalyanCessRate(BigDecimal value) {
        this.krishiKalyanCessRate = value;
    }

    /**
     * Gets the value of the salesTaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalesTaxRate() {
        return salesTaxRate;
    }

    /**
     * Sets the value of the salesTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalesTaxRate(BigDecimal value) {
        this.salesTaxRate = value;
    }

    /**
     * Gets the value of the surchargeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurchargeRate() {
        return surchargeRate;
    }

    /**
     * Sets the value of the surchargeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurchargeRate(BigDecimal value) {
        this.surchargeRate = value;
    }

    /**
     * Gets the value of the totalTaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTaxRate() {
        return totalTaxRate;
    }

    /**
     * Sets the value of the totalTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTaxRate(BigDecimal value) {
        this.totalTaxRate = value;
    }

    /**
     * Gets the value of the premiumAfterTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremiumAfterTax() {
        return premiumAfterTax;
    }

    /**
     * Sets the value of the premiumAfterTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremiumAfterTax(BigDecimal value) {
        this.premiumAfterTax = value;
    }

}
