//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for StampDuty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StampDuty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stampDutyCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="stampDutyEffectiveDateStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sumInsuredAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="maxSumInsuredAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="premiumAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="stampDutyDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="stampDutyRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="registrationNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalStampDuty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StampDuty", propOrder = {
    "stateName",
    "productCode",
    "stampDutyCategory",
    "transactionType",
    "transactionDate",
    "stampDutyEffectiveDateStatus",
    "sumInsuredAmount",
    "maxSumInsuredAmount",
    "premiumAmount",
    "stampDutyDate",
    "stampDutyRate",
    "registrationNo",
    "totalStampDuty"
})
public class StampDuty
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected String stateName;
    @XmlElement(required = true)
    protected String productCode;
    @XmlElement(required = true)
    protected String stampDutyCategory;
    @XmlElement(required = true)
    protected String transactionType;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date transactionDate;
    @XmlElement(required = true)
    protected String stampDutyEffectiveDateStatus;
    @XmlElement(required = true)
    protected BigDecimal sumInsuredAmount;
    @XmlElement(required = true)
    protected BigDecimal maxSumInsuredAmount;
    @XmlElement(required = true)
    protected BigDecimal premiumAmount;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date stampDutyDate;
    @XmlElement(required = true)
    protected BigDecimal stampDutyRate;
    @XmlElement(required = true)
    protected String registrationNo;
    @XmlElement(required = true)
    protected BigDecimal totalStampDuty;

    /**
     * Gets the value of the stateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * Sets the value of the stateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateName(String value) {
        this.stateName = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the stampDutyCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStampDutyCategory() {
        return stampDutyCategory;
    }

    /**
     * Sets the value of the stampDutyCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStampDutyCategory(String value) {
        this.stampDutyCategory = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(Date value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the stampDutyEffectiveDateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStampDutyEffectiveDateStatus() {
        return stampDutyEffectiveDateStatus;
    }

    /**
     * Sets the value of the stampDutyEffectiveDateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStampDutyEffectiveDateStatus(String value) {
        this.stampDutyEffectiveDateStatus = value;
    }

    /**
     * Gets the value of the sumInsuredAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumInsuredAmount() {
        return sumInsuredAmount;
    }

    /**
     * Sets the value of the sumInsuredAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumInsuredAmount(BigDecimal value) {
        this.sumInsuredAmount = value;
    }

    /**
     * Gets the value of the maxSumInsuredAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxSumInsuredAmount() {
        return maxSumInsuredAmount;
    }

    /**
     * Sets the value of the maxSumInsuredAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxSumInsuredAmount(BigDecimal value) {
        this.maxSumInsuredAmount = value;
    }

    /**
     * Gets the value of the premiumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremiumAmount() {
        return premiumAmount;
    }

    /**
     * Sets the value of the premiumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremiumAmount(BigDecimal value) {
        this.premiumAmount = value;
    }

    /**
     * Gets the value of the stampDutyDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getStampDutyDate() {
        return stampDutyDate;
    }

    /**
     * Sets the value of the stampDutyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStampDutyDate(Date value) {
        this.stampDutyDate = value;
    }

    /**
     * Gets the value of the stampDutyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStampDutyRate() {
        return stampDutyRate;
    }

    /**
     * Sets the value of the stampDutyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStampDutyRate(BigDecimal value) {
        this.stampDutyRate = value;
    }

    /**
     * Gets the value of the registrationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNo() {
        return registrationNo;
    }

    /**
     * Sets the value of the registrationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNo(String value) {
        this.registrationNo = value;
    }

    /**
     * Gets the value of the totalStampDuty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalStampDuty() {
        return totalStampDuty;
    }

    /**
     * Sets the value of the totalStampDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalStampDuty(BigDecimal value) {
        this.totalStampDuty = value;
    }

}
