//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 08:39:48 AM IST 
//


package com.icicilombard.marine.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SubProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubProduct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sumInsured" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="subProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loading" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="typeOfCargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="perSendingLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="perLocationLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="exposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="policyStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rackRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="netRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="discountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loadingAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="serviceTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="stampDuty" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="netPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pmlLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="excessAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="salesExposurePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://marine.icicilombard.com}Messages" minOccurs="0"/>
 *         &lt;element name="subProductLevelApproval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="brokeragePremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="policyRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="approverAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uwLevel" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="taxDetails" type="{http://marine.icicilombard.com}TaxDetails"/>
 *         &lt;element name="selectedBothBasicAndSRCC" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ninetyFivePercentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ninetyFivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fivePercentPremium" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fivePercentRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubProduct", propOrder = {
    "sumInsured",
    "subProductName",
    "loading",
    "discount",
    "typeOfCargo",
    "perSendingLimit",
    "perLocationLimit",
    "exposurePremium",
    "totalPremium",
    "policyStatus",
    "rackRate",
    "netRate",
    "discountAmount",
    "loadingAmount",
    "serviceTax",
    "stampDuty",
    "netPremium",
    "pmlLimit",
    "excessAmount",
    "salesExposurePremium",
    "messages",
    "subProductLevelApproval",
    "brokeragePremium",
    "policyRate",
    "approverAuthority",
    "uwLevel",
    "taxDetails",
    "selectedBothBasicAndSRCC",
    "ninetyFivePercentPremium",
    "ninetyFivePercentRate",
    "fivePercentPremium",
    "fivePercentRate"
})
public class SubProduct
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlElement(required = true)
    protected BigDecimal sumInsured;
    @XmlElement(required = true)
    protected String subProductName;
    protected BigDecimal loading;
    protected BigDecimal discount;
    @XmlElement(required = true)
    protected String typeOfCargo;
    @XmlElement(required = true)
    protected BigDecimal perSendingLimit;
    @XmlElement(required = true)
    protected BigDecimal perLocationLimit;
    protected BigDecimal exposurePremium;
    protected BigDecimal totalPremium;
    protected String policyStatus;
    protected BigDecimal rackRate;
    protected BigDecimal netRate;
    protected BigDecimal discountAmount;
    protected BigDecimal loadingAmount;
    protected BigDecimal serviceTax;
    protected BigDecimal stampDuty;
    protected BigDecimal netPremium;
    protected BigDecimal pmlLimit;
    protected BigDecimal excessAmount;
    protected BigDecimal salesExposurePremium;
    protected Messages messages;
    protected String subProductLevelApproval;
    protected BigDecimal brokeragePremium;
    protected BigDecimal policyRate;
    @XmlElement(required = true)
    protected String approverAuthority;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "integer")
    protected Integer uwLevel;
    @XmlElement(required = true)
    protected TaxDetails taxDetails;
    protected boolean selectedBothBasicAndSRCC;
    protected BigDecimal ninetyFivePercentPremium;
    protected BigDecimal ninetyFivePercentRate;
    protected BigDecimal fivePercentPremium;
    protected BigDecimal fivePercentRate;

    /**
     * Gets the value of the sumInsured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumInsured() {
        return sumInsured;
    }

    /**
     * Sets the value of the sumInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumInsured(BigDecimal value) {
        this.sumInsured = value;
    }

    /**
     * Gets the value of the subProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubProductName() {
        return subProductName;
    }

    /**
     * Sets the value of the subProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubProductName(String value) {
        this.subProductName = value;
    }

    /**
     * Gets the value of the loading property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoading() {
        return loading;
    }

    /**
     * Sets the value of the loading property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoading(BigDecimal value) {
        this.loading = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscount(BigDecimal value) {
        this.discount = value;
    }

    /**
     * Gets the value of the typeOfCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfCargo() {
        return typeOfCargo;
    }

    /**
     * Sets the value of the typeOfCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfCargo(String value) {
        this.typeOfCargo = value;
    }

    /**
     * Gets the value of the perSendingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerSendingLimit() {
        return perSendingLimit;
    }

    /**
     * Sets the value of the perSendingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerSendingLimit(BigDecimal value) {
        this.perSendingLimit = value;
    }

    /**
     * Gets the value of the perLocationLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerLocationLimit() {
        return perLocationLimit;
    }

    /**
     * Sets the value of the perLocationLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerLocationLimit(BigDecimal value) {
        this.perLocationLimit = value;
    }

    /**
     * Gets the value of the exposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExposurePremium() {
        return exposurePremium;
    }

    /**
     * Sets the value of the exposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExposurePremium(BigDecimal value) {
        this.exposurePremium = value;
    }

    /**
     * Gets the value of the totalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPremium() {
        return totalPremium;
    }

    /**
     * Sets the value of the totalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPremium(BigDecimal value) {
        this.totalPremium = value;
    }

    /**
     * Gets the value of the policyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyStatus() {
        return policyStatus;
    }

    /**
     * Sets the value of the policyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyStatus(String value) {
        this.policyStatus = value;
    }

    /**
     * Gets the value of the rackRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRackRate() {
        return rackRate;
    }

    /**
     * Sets the value of the rackRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRackRate(BigDecimal value) {
        this.rackRate = value;
    }

    /**
     * Gets the value of the netRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetRate() {
        return netRate;
    }

    /**
     * Sets the value of the netRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetRate(BigDecimal value) {
        this.netRate = value;
    }

    /**
     * Gets the value of the discountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Sets the value of the discountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountAmount(BigDecimal value) {
        this.discountAmount = value;
    }

    /**
     * Gets the value of the loadingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoadingAmount() {
        return loadingAmount;
    }

    /**
     * Sets the value of the loadingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoadingAmount(BigDecimal value) {
        this.loadingAmount = value;
    }

    /**
     * Gets the value of the serviceTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceTax() {
        return serviceTax;
    }

    /**
     * Sets the value of the serviceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceTax(BigDecimal value) {
        this.serviceTax = value;
    }

    /**
     * Gets the value of the stampDuty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStampDuty() {
        return stampDuty;
    }

    /**
     * Sets the value of the stampDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStampDuty(BigDecimal value) {
        this.stampDuty = value;
    }

    /**
     * Gets the value of the netPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPremium() {
        return netPremium;
    }

    /**
     * Sets the value of the netPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPremium(BigDecimal value) {
        this.netPremium = value;
    }

    /**
     * Gets the value of the pmlLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPmlLimit() {
        return pmlLimit;
    }

    /**
     * Sets the value of the pmlLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPmlLimit(BigDecimal value) {
        this.pmlLimit = value;
    }

    /**
     * Gets the value of the excessAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessAmount() {
        return excessAmount;
    }

    /**
     * Sets the value of the excessAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessAmount(BigDecimal value) {
        this.excessAmount = value;
    }

    /**
     * Gets the value of the salesExposurePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalesExposurePremium() {
        return salesExposurePremium;
    }

    /**
     * Sets the value of the salesExposurePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalesExposurePremium(BigDecimal value) {
        this.salesExposurePremium = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link Messages }
     *     
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Messages }
     *     
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the subProductLevelApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubProductLevelApproval() {
        return subProductLevelApproval;
    }

    /**
     * Sets the value of the subProductLevelApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubProductLevelApproval(String value) {
        this.subProductLevelApproval = value;
    }

    /**
     * Gets the value of the brokeragePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBrokeragePremium() {
        return brokeragePremium;
    }

    /**
     * Sets the value of the brokeragePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBrokeragePremium(BigDecimal value) {
        this.brokeragePremium = value;
    }

    /**
     * Gets the value of the policyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPolicyRate() {
        return policyRate;
    }

    /**
     * Sets the value of the policyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPolicyRate(BigDecimal value) {
        this.policyRate = value;
    }

    /**
     * Gets the value of the approverAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproverAuthority() {
        return approverAuthority;
    }

    /**
     * Sets the value of the approverAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproverAuthority(String value) {
        this.approverAuthority = value;
    }

    /**
     * Gets the value of the uwLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getUwLevel() {
        return uwLevel;
    }

    /**
     * Sets the value of the uwLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUwLevel(Integer value) {
        this.uwLevel = value;
    }

    /**
     * Gets the value of the taxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetails }
     *     
     */
    public TaxDetails getTaxDetails() {
        return taxDetails;
    }

    /**
     * Sets the value of the taxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetails }
     *     
     */
    public void setTaxDetails(TaxDetails value) {
        this.taxDetails = value;
    }

    /**
     * Gets the value of the selectedBothBasicAndSRCC property.
     * 
     */
    public boolean isSelectedBothBasicAndSRCC() {
        return selectedBothBasicAndSRCC;
    }

    /**
     * Sets the value of the selectedBothBasicAndSRCC property.
     * 
     */
    public void setSelectedBothBasicAndSRCC(boolean value) {
        this.selectedBothBasicAndSRCC = value;
    }

    /**
     * Gets the value of the ninetyFivePercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNinetyFivePercentPremium() {
        return ninetyFivePercentPremium;
    }

    /**
     * Sets the value of the ninetyFivePercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNinetyFivePercentPremium(BigDecimal value) {
        this.ninetyFivePercentPremium = value;
    }

    /**
     * Gets the value of the ninetyFivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNinetyFivePercentRate() {
        return ninetyFivePercentRate;
    }

    /**
     * Sets the value of the ninetyFivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNinetyFivePercentRate(BigDecimal value) {
        this.ninetyFivePercentRate = value;
    }

    /**
     * Gets the value of the fivePercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFivePercentPremium() {
        return fivePercentPremium;
    }

    /**
     * Sets the value of the fivePercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFivePercentPremium(BigDecimal value) {
        this.fivePercentPremium = value;
    }

    /**
     * Gets the value of the fivePercentRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFivePercentRate() {
        return fivePercentRate;
    }

    /**
     * Sets the value of the fivePercentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFivePercentRate(BigDecimal value) {
        this.fivePercentRate = value;
    }

}
